### ISSUE TITLE
[1.183.001.2] Exception thrown on startup

### ISSUE THREAD

**Issue by SeeJayEmm** [midspace/SEToolbox#107]
The exception below is thrown when I start SE Toolbox. I have tried removing and reinstalling, running it as admin, and running it in Win7 compat mode.

2017-08-24 15:10:07,686 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64
SEBinVersion: 1.183.100
ProcessorCount: 4
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-US
CurrentCulture: 

Files:
2017-08-24T14:58:13.5584096-04:00	21,554,224		HavokWrapper.dll
2017-06-02T07:49:12.0000000-04:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2015-11-23T08:03:56.0000000-05:00	200,704	0.86.5.0	ICSharpCode.SharpZipLib.dll
2017-08-24T14:58:13.4983648-04:00	34,864	1.0.0.0	InfinarioSDK.dll
2017-03-08T17:26:22.0000000-05:00	276,480	2.0.8.0	log4net.dll
2015-06-25T17:21:43.8442613-04:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2015-06-25T17:21:53.6828240-04:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2017-08-24T14:58:14.7065728-04:00	68,144	1.0.0.0	Sandbox.Common.dll
2017-08-24T14:58:17.1453871-04:00	6,706,224	1.0.0.0	Sandbox.Game.dll
2017-08-24T14:58:14.7921985-04:00	364,592	1.0.0.0	Sandbox.Graphics.dll
2017-08-23T17:11:38.0000000-04:00	1,304,064	01.183.001.2	SEToolbox.exe
2017-06-02T07:49:12.0000000-04:00	745		SEToolbox.exe.config
2017-06-20T18:09:16.0000000-04:00	29,184	1.0.0.0	SEToolbox.ImageLibrary.dll
2017-08-23T17:11:36.0000000-04:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2017-08-23T17:11:38.0000000-04:00	2,160,128		SEToolbox.pdb
2017-08-23T16:23:24.0000000-04:00	51,712	1.0.0.0	SEToolboxUpdate.exe
2017-08-24T14:58:15.0764898-04:00	269,872	3.1.0	SharpDX.dll
2017-08-24T14:58:15.2804939-04:00	413,232	1.0.0.0	SpaceEngineers.Game.dll
2017-08-24T14:58:15.3468145-04:00	55,856	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2017-08-24T14:58:17.1028404-04:00	11,238,448	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2017-08-24T14:58:15.4035336-04:00	683,568		SteamSDK.dll
2017-08-17T12:19:50.3011887-04:00	242,976	03.75.32.07	steam_api64.dll
2017-08-24T14:58:15.5234092-04:00	302,128	1.0.98.0	System.Data.SQLite.dll
2013-03-09T16:25:10.0000000-05:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2017-08-24T14:58:15.4993896-04:00	22,576	1.0.0.0	VRage.Ansel.dll
2017-08-24T14:58:17.5649006-04:00	73,776	1.0.0.0	VRage.Audio.dll
2017-08-24T14:58:15.5714420-04:00	446,000	1.0.0.0	VRage.dll
2017-08-24T14:58:15.6203506-04:00	1,032,752	1.0.0.0	VRage.Game.dll
2017-08-24T14:58:15.9335714-04:00	3,369,008	1.0.0.0	VRage.Game.XmlSerializers.dll
2017-08-24T14:58:15.7204213-04:00	97,328	1.0.0.0	VRage.Input.dll
2017-08-24T14:58:15.7084133-04:00	668,208	1.0.0.0	VRage.Library.dll
2017-08-24T14:58:15.7914685-04:00	520,752	1.0.0.0	VRage.Math.dll
2017-08-24T14:58:17.6195637-04:00	78,384		VRage.Native.dll
2017-08-24T14:58:15.8294984-04:00	105,008	1.0.0.0	VRage.OpenVRWrapper.dll
2017-08-24T14:58:15.8495126-04:00	327,216	1.0.0.0	VRage.Render.dll
2017-08-24T14:58:18.4899608-04:00	914,992	1.0.0.0	VRage.Render11.dll
2015-06-29T00:00:10.0000000-04:00	71,168	2.3.2	WPFLocalizeExtension.dll
2016-05-04T23:32:16.0000000-04:00	27,648	1.2.2	XAMLMarkupExtensions.dll

System.TypeInitializationException: The type initializer for 'SEToolbox.Interop.SpaceEngineersCore' threw an exception. ---> System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[VRage.MyLanguagesEnum,VRage.MyTexts+LanguageDescription]' to type 'System.Collections.Generic.Dictionary`2[System.Int32,VRage.MyTexts+LanguageDescription]'.
   at SEToolbox.Support.ReflectionUtil.GetStaticField[T](Type type, String fieldName)
   at SEToolbox.Interop.SpaceEngineersApi.AddLanguage(MyLanguagesEnum id, String cultureName, String subcultureName, String displayName, Single guiTextScale, Boolean isCommunityLocalized) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersApi.cs:line 319
   at SEToolbox.Interop.SpaceEngineersApi.LoadLocalization() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersApi.cs:line 267
   at SEToolbox.Interop.SpaceEngineersCore..ctor() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 55
   at SEToolbox.Interop.SpaceEngineersCore..cctor() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 22
   --- End of inner exception stack trace ---
   at SEToolbox.Interop.SpaceEngineersCore.LoadDefinitions()
   at SEToolbox.CoreToolbox.Load(String[] args) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\CoreToolbox.cs:line 181
   at SEToolbox.App.OnStartup(Object sender, StartupEventArgs e) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\App.xaml.cs:line 94
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by midspace** [comment]
I have released an update to fix the issue.
https://github.com/midspace/SEToolbox/releases/latest

**Comment by SeeJayEmm** [comment]
Thanks for the quick turn-around.
