### ISSUE TITLE
[1.183.100.1] Sequence contains no elements

### ISSUE THREAD

**Issue by SeeJayEmm** [midspace/SEToolbox#108]
When I attempt to delete a Character from my saved game I get the following error:

> Sequence contains no elements.

Event Log:
2017-08-24 18:12:47.530 - Thread:   1 ->  ERROR: Loading screen failed
2017-08-24 18:12:47.534 - Thread:   1 ->  Exception occured: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Sandbox.Engine.Multiplayer.MyMultiplayerClient.LoadMembersFromWorld(List`1 clients)
   at Sandbox.Game.World.MySession.LoadMembersFromWorld(MyObjectBuilder_World world, MyMultiplayerBase multiplayerSession)
   at Sandbox.Game.World.MySession.LoadMultiplayer(MyObjectBuilder_World world, MyMultiplayerBase multiplayerSession)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.RunLoadingAction()
   at Sandbox.Game.Gui.MyGuiScreenLoading.RunLoad()

For what it's worth, this is my DS world and my SE client has been reporting this world as corrupt since the last update. I was hoping it was an issue w/ the update and not the world but this is the exact same error that's in my client log when I try to connect.

When I attempt a repair it reports "detected no issues". 

If this is something that a repair should/could detect and fix I am more than happy to zip up the world and provide it as an example. If not feel free to close this issue.

Thanks

**Comment by midspace** [comment]
I should probably close this one.
I'm not sure why I missed this one. It was probably when I about to go on holiday, and was buried under other emails when I got back.
