### ISSUE TITLE
Couldn't Load file or assembly - Win10Prox64

### ISSUE THREAD

**Issue by nugunsknight** [midspace/SEToolbox#109]
![image](https://user-images.githubusercontent.com/2825270/29756611-3d705b96-8b73-11e7-9f2a-154e33b330df.png)

Get this error with the most recent build. Tried the MSI and the zip files. Reinstalled SE, unsubbed from all mods, still nothing.

EVENT LOG:

2017-08-27 21:27:21,321 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" /X /B
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: G:\Steam\SteamApps\common\SpaceEngineers\Bin64
SEBinVersion: 
ProcessorCount: 12
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-US
CurrentCulture: en-US

Files:
2017-06-02T07:49:12.0000000-04:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2015-11-23T08:03:56.0000000-05:00	200,704	0.86.5.0	ICSharpCode.SharpZipLib.dll
2017-03-08T17:26:22.0000000-05:00	276,480	2.0.8.0	log4net.dll
2017-08-25T07:33:06.0000000-04:00	1,304,064	01.183.100.1	SEToolbox.exe
2017-06-02T07:49:12.0000000-04:00	745		SEToolbox.exe.config
2017-06-20T18:09:16.0000000-04:00	29,184	1.0.0.0	SEToolbox.ImageLibrary.dll
2017-08-25T07:33:04.0000000-04:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2017-08-25T07:33:06.0000000-04:00	2,160,128		SEToolbox.pdb
2017-08-23T16:23:24.0000000-04:00	51,712	1.0.0.0	SEToolboxUpdate.exe
2013-03-09T16:25:10.0000000-05:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2015-06-29T00:00:10.0000000-04:00	71,168	2.3.2	WPFLocalizeExtension.dll
2016-05-04T23:32:16.0000000-04:00	27,648	1.2.2	XAMLMarkupExtensions.dll

System.IO.FileNotFoundException: Could not load file or assembly 'VRage.Math, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'VRage.Math, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at SEToolbox.CoreToolbox.Load(String[] args)
   at SEToolbox.App.OnStartup(Object sender, StartupEventArgs e) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\App.xaml.cs:line 94
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by midspace** [comment]
It does not appear that you allowed it to copy the needed files from the Space Engineers installation.


1. Once your press continue, you will be prompted with a warning. This warning will appear every time there is a change to Space Engineers, as it will need to copy the required files to it's own installation directory, which requires UAC permission.
![](http://i.imgur.com/sM8E2Zm.png)
1. Once you confirm UAC for the SEToolboxUpdate.exe, it will copy the required files from Space Engineers and run.<br/>
UAC requires an Administrator account to allow changes.
![](http://i.imgur.com/CDW8yTQ.png)

**Comment by nugunsknight** [comment]
I have UAC prompts set to never ask and the toolbox worked the last time I ran it back in June when I was still running Windows 7. Running as admin also had no luck.

**Comment by midspace** [comment]
It sounds like something ( probably windows Defender Smart Screen) may be interfering.

Can you try the following?

1. Open Windows Explorer to the following directory:
C:\Program Files (x86)\MidSpace\SEToolbox

2. Run via following with   Windows Key +R
C:\Program Files (x86)\MidSpace\SEToolbox\SEToolboxUpdate.exe /B

Normally it should ask to elevate privileges.
It's purpose is to copy several SpaceEngineers files in the directory in step 1.

If it does not, you will need to look into any prompts that windows or your antivirus shows you that it is blocking programs.

**Comment by nugunsknight** [comment]
Using CMD did not work. BUT...

FIXED:

Disabled Smart Screen and attempted again with a successful copy and startup.

Smart screen never gave me a prompt concerning the program and after disabling smart screen it worked. Yet another useless feature I will leave disabled in Windows 10.

Thanks for the assistance. Hope this helps future Windows 10 users!
