### ISSUE TITLE
getting this when trying to start the program

### ISSUE THREAD

**Issue by tedderz** [midspace/SEToolbox#126]
```
Log Name:      Application
Source:        SEToolbox.exe
Date:          2/2/2018 6:00:59 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Gamer
Description:
2018-02-02 18:00:59,404 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: D:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "D:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: D:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: D:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Bin64
SEBinVersion: 1.186.29
ProcessorCount: 4
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: True
CurrentUICulture: en-US
CurrentCulture: en-US

Files:
2018-02-02T15:08:32.6260000-05:00	21,579,824		HavokWrapper.dll
2017-06-02T09:49:12.0000000-04:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2015-11-23T10:03:56.0000000-05:00	200,704	0.86.5.0	ICSharpCode.SharpZipLib.dll
2017-03-08T19:26:22.0000000-05:00	276,480	2.0.8.0	log4net.dll
2017-12-07T15:43:51.6750000-05:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2017-12-07T15:43:51.6760000-05:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2018-02-02T15:08:36.8250000-05:00	72,240	1.0.0.0	Sandbox.Common.dll
2018-02-02T15:08:32.6490000-05:00	6,881,840	1.0.0.0	Sandbox.Game.dll
2018-02-02T15:08:32.6490000-05:00	385,584	1.0.0.0	Sandbox.Graphics.dll
2018-02-03T09:05:16.0000000-05:00	1,299,456	01.186.29.0	SEToolbox.exe
2017-06-02T09:49:12.0000000-04:00	745		SEToolbox.exe.config
2018-02-02T07:56:20.0000000-05:00	29,184	1.0.0.0	SEToolbox.ImageLibrary.dll
2018-02-03T09:05:14.0000000-05:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2018-02-03T09:05:16.0000000-05:00	2,174,464		SEToolbox.pdb
2018-02-02T07:56:20.0000000-05:00	52,224	1.0.0.0	SEToolboxUpdate.exe
2018-02-02T15:08:32.6510000-05:00	269,872	3.1.0	SharpDX.dll
2018-02-02T15:08:32.6510000-05:00	433,712	1.0.0.0	SpaceEngineers.Game.dll
2018-02-02T15:08:36.9280000-05:00	58,928	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2018-02-02T15:08:32.6540000-05:00	4,447,792	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2018-02-02T15:08:32.6550000-05:00	683,568		SteamSDK.dll
2017-12-07T15:45:21.1380000-05:00	242,976	03.75.32.07	steam_api64.dll
2018-02-02T15:08:32.6560000-05:00	323,632	1.0.102.0	System.Data.SQLite.dll
2013-03-09T18:25:10.0000000-05:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2018-02-02T15:08:39.0280000-05:00	23,600	1.0.0.0	VRage.Ansel.dll
2018-02-02T15:08:39.0280000-05:00	66,608	1.0.0.0	VRage.Audio.dll
2018-02-02T15:08:32.6560000-05:00	464,432	1.0.0.0	VRage.dll
2018-02-02T15:08:32.6570000-05:00	1,225,264	1.0.0.0	VRage.Game.dll
2018-02-02T15:08:32.6570000-05:00	6,986,288	1.0.0.0	VRage.Game.XmlSerializers.dll
2018-02-02T15:08:39.8640000-05:00	97,840	1.0.0.0	VRage.Input.dll
2018-02-02T15:08:32.6580000-05:00	685,104	1.0.0.0	VRage.Library.dll
2018-02-02T15:08:32.6590000-05:00	532,528	1.0.0.0	VRage.Math.dll
2018-02-02T15:08:38.5190000-05:00	190,512		VRage.Native.dll
2018-02-02T15:08:38.5700000-05:00	105,008	1.0.0.0	VRage.OpenVRWrapper.dll
2018-02-02T15:08:32.6600000-05:00	324,144	1.0.0.0	VRage.Render.dll
2018-02-02T15:08:32.6610000-05:00	983,088	1.0.0.0	VRage.Render11.dll
2015-06-29T02:00:10.0000000-04:00	71,168	2.3.2	WPFLocalizeExtension.dll
2016-05-05T01:32:16.0000000-04:00	27,648	1.2.2	XAMLMarkupExtensions.dll

System.TypeInitializationException: The type initializer for 'SEToolbox.Interop.SpaceEngineersCore' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Engine.Utils.MyConfigBase.Load()
   at SEToolbox.Interop.SpaceEngineersCore..ctor() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 42
   at SEToolbox.Interop.SpaceEngineersCore..cctor() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 23
   --- End of inner exception stack trace ---
   at SEToolbox.Interop.SpaceEngineersCore.LoadDefinitions()
   at SEToolbox.CoreToolbox.Load(String[] args) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\CoreToolbox.cs:line 181
   at SEToolbox.App.OnStartup(Object sender, StartupEventArgs e) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\App.xaml.cs:line 94
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by midspace** [comment]
At the moment, I'm unable to reproduce this issue.
I'm not sure what's wrong.

Is the game working properly?

**Comment by tedderz** [comment]
I was able to figure out what the issue was.  I deleted my preferences
for the game, and that seemed to fix the problem. 

On 2018-02-02 19:21, midspace wrote:

> At the moment, I'm unable to reproduce this issue.
> I'm not sure what's wrong. 
> 
> Is the game working properly? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/midspace/SEToolbox/issues/126#issuecomment-362749693
[2]

**Comment by midspace** [comment]
It's good to hear that you got it working

I know that Keen have changed the configuration settings a little, but I'm unsure how much.
I'll keep this in mind if other people have the same issue in the future.
