### ISSUE TITLE
Crash during ResourceReport with custom modded ores.

### ISSUE THREAD

**Issue by midspace** [midspace/SEToolbox#143]
```
2018-08-12 16:07:03,556 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: E:\Steam games\steamapps\common\SpaceEngineers\Bin64
SEBinVersion: 1.187.101
ProcessorCount: 12
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-US
CurrentCulture: 
Times started total: 21
Times started since last reset: 21
Times started since game update: 19

Files:
2018-08-07T11:33:52.8058991-06:00	25,060,400		HavokWrapper.dll
2017-06-02T07:49:12.0000000-06:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2017-03-08T17:26:22.0000000-07:00	276,480	2.0.8.0	log4net.dll
2015-08-18T20:43:39.1269887-06:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2015-08-18T20:43:40.5049042-06:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2018-08-07T11:33:54.7277123-06:00	75,312	1.0.0.0	Sandbox.Common.dll
2018-08-07T11:33:52.8088908-06:00	7,125,040	1.0.0.0	Sandbox.Game.dll
2018-08-07T11:33:52.8098890-06:00	388,656	1.0.0.0	Sandbox.Graphics.dll
2018-08-07T11:33:54.7297068-06:00	17,968	1.0.0.0	Sandbox.RenderDirect.dll
2018-07-22T17:35:12.0000000-06:00	1,321,984	01.187.87.3	SEToolbox.exe
2017-06-02T07:49:12.0000000-06:00	745		SEToolbox.exe.config
2018-07-19T19:44:00.0000000-06:00	62,464	1.0.0.0	SEToolbox.ImageLibrary.dll
2018-07-22T17:35:08.0000000-06:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2018-07-22T17:35:12.0000000-06:00	2,209,280		SEToolbox.pdb
2018-07-19T20:09:18.0000000-06:00	53,248	1.0.0.0	SEToolboxUpdate.exe
2018-08-07T11:33:52.8098890-06:00	489,008	3.1.0	SharpDX.Direct2D1.dll
2018-08-07T11:33:52.8108858-06:00	288,304	3.1.0	SharpDX.Direct3D11.dll
2018-08-07T11:33:52.8118830-06:00	269,872	3.1.0	SharpDX.dll
2018-08-07T11:33:54.7317011-06:00	139,824	3.1.0	SharpDX.DXGI.dll
2018-08-07T11:33:52.8118830-06:00	451,632	1.0.0.0	SpaceEngineers.Game.dll
2018-08-07T11:33:54.7646128-06:00	60,464	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2018-08-07T11:33:52.8188642-06:00	4,502,576	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2018-08-07T11:33:52.8188642-06:00	329,264	11.0.0	Steamworks.NET.dll
2018-07-19T11:17:37.9812152-06:00	250,656	04.28.51.07	steam_api64.dll
2018-08-07T11:33:52.8198616-06:00	323,632	1.0.102.0	System.Data.SQLite.dll
2013-03-09T16:25:10.0000000-07:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2018-08-07T11:33:54.8743194-06:00	24,112	1.0.0.0	VRage.Ansel.dll
2018-08-07T11:33:54.8743194-06:00	68,656	1.0.0.0	VRage.Audio.dll
2018-08-07T11:33:52.8198616-06:00	493,616	1.0.0.0	VRage.dll
2018-08-07T11:33:52.8248484-06:00	1,312,816	1.0.0.0	VRage.Game.dll
2018-08-07T11:33:52.8248484-06:00	7,029,808	1.0.0.0	VRage.Game.XmlSerializers.dll
2018-08-07T11:33:55.6592191-06:00	98,352	1.0.0.0	VRage.Input.dll
2018-08-07T11:33:52.8258455-06:00	712,240	1.0.0.0	VRage.Library.dll
2018-08-07T11:33:52.8268434-06:00	562,224	1.0.0.0	VRage.Math.dll
2018-08-07T11:33:55.0598227-06:00	190,512		VRage.Native.dll
2018-08-07T11:33:54.9830284-06:00	105,008	1.0.0.0	VRage.OpenVRWrapper.dll
2018-08-07T11:33:52.8268434-06:00	351,280	1.0.0.0	VRage.Render.dll
2018-08-07T11:33:52.8358231-06:00	983,088	1.0.0.0	VRage.Render11.dll
2018-03-27T14:51:20.0000000-06:00	77,824	3.0.1.0	WPFLocalizeExtension.dll
2018-01-08T19:35:48.0000000-07:00	27,648	1.2.2	XAMLMarkupExtensions.dll

System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at SEToolbox.Models.ResourceReportModel.GenerateReport() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\ResourceReportModel.cs:line 364
   at SEToolbox.ViewModels.ResourceReportViewModel.GenerateExecuted() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\ResourceReportViewModel.cs:line 163
   at SEToolbox.Services.DelegateCommand.Execute() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 72
   at SEToolbox.Services.DelegateCommand.System.Windows.Input.ICommand.Execute(Object parameter) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 154
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by midspace** [comment]
Fixed and release.
