### ISSUE TITLE
toolbox crashes when opening sandbox

### ISSUE THREAD

**Issue by OminiData** [midspace/SEToolbox#145]
- [x] Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.
- [x] Ensure that the issue is reproducible for testing. You may be requested to provide a link to a test world if we cannot reproduce it with your information.
- [x] Retrieve the Event Log from when SEToolbox crashed. Read the following [instructions](https://github.com/midspace/SEToolbox/wiki/Reporting-bugs) on retrieving the event log.

**SEToolbox Version:** 01.187.87
**SE Version:** 1.187.204

### SEToolbox crashed
trying to open up the sandbox

### Steps to Reproduce
1. was trying to open the sandbox file?
2. Write all of the steps here.

### SEToolbox Event Log
```
Application: SEToolbox.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingFieldException
   at SEToolbox.Interop.Asteroids.MyVoxelMap.Dispose(Boolean)

   at SEToolbox.Interop.Asteroids.MyVoxelMap.Finalize()
```
[sandbox.zip](https://github.com/midspace/SEToolbox/files/2321804/sandbox.zip)

**Comment by midspace** [comment]
It looks to be a new breaking change in the game with the recent update.

```
2018-08-26 14:34:25,801 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe"
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64
SEBinVersion: 1.187.204
ProcessorCount: 8
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: True
CurrentUICulture: en-US
CurrentCulture:
Times started total: 6
Times started since last reset: 6
Times started since game update: 4
Files:
2018-08-25T09:18:07.4296492-07:00	25,057,840	HavokWrapper.dll
2017-06-02T07:49:12.0000000-07:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2017-03-08T17:26:22.0000000-08:00	276,480	2.0.8.0	log4net.dll
2015-04-30T10:08:48.0000000-07:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2015-04-30T10:08:48.0000000-07:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2018-08-25T09:18:08.3407013-07:00	75,312	1.0.0.0	Sandbox.Common.dll
2018-08-25T09:18:07.4346495-07:00	7,143,984	1.0.0.0	Sandbox.Game.dll
2018-08-25T09:18:07.4346495-07:00	390,192	1.0.0.0	Sandbox.Graphics.dll
2018-08-25T09:18:08.7497247-07:00	17,968	1.0.0.0	Sandbox.RenderDirect.dll
2018-08-21T10:27:26.0000000-07:00	1,334,784	01.187.87.6	SEToolbox.exe
2017-06-02T07:49:12.0000000-07:00	745	SEToolbox.exe.config
2018-08-21T09:21:42.0000000-07:00	62,464	1.0.0.0	SEToolbox.ImageLibrary.dll
2018-08-21T10:27:24.0000000-07:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2018-08-21T10:27:26.0000000-07:00	2,233,856	SEToolbox.pdb
2018-08-21T09:21:42.0000000-07:00	53,248	1.0.0.0	SEToolboxUpdate.exe
2018-08-25T09:18:07.4356495-07:00	489,008	3.1.0	SharpDX.Direct2D1.dll
2018-08-25T09:18:07.4356495-07:00	288,304	3.1.0	SharpDX.Direct3D11.dll
2018-08-25T09:18:07.4366496-07:00	269,872	3.1.0	SharpDX.dll
2018-08-25T09:18:09.0357411-07:00	139,824	3.1.0	SharpDX.DXGI.dll
2018-08-25T09:18:07.4376497-07:00	452,656	1.0.0.0	SpaceEngineers.Game.dll
2018-08-25T09:18:09.3917614-07:00	60,464	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2018-08-25T09:18:07.4376497-07:00	4,542,512	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2018-08-25T09:18:07.4386497-07:00	329,264	11.0.0	Steamworks.NET.dll
2018-07-19T10:56:41.7862716-07:00	250,656	04.28.51.07	steam_api64.dll
2018-08-25T09:18:07.4386497-07:00	323,632	1.0.102.0	System.Data.SQLite.dll
2013-03-09T16:25:10.0000000-08:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2018-08-25T09:18:09.3927615-07:00	24,112	1.0.0.0	VRage.Ansel.dll
2018-08-25T09:18:09.3937615-07:00	68,656	1.0.0.0	VRage.Audio.dll
2018-08-25T09:18:07.4386497-07:00	494,128	1.0.0.0	VRage.dll
2018-08-25T09:18:07.4396498-07:00	1,316,912	1.0.0.0	VRage.Game.dll
2018-08-25T09:18:07.4416499-07:00	7,038,000	1.0.0.0	VRage.Game.XmlSerializers.dll
2018-08-25T09:18:09.3947616-07:00	98,352	1.0.0.0	VRage.Input.dll
2018-08-25T09:18:07.4416499-07:00	713,776	1.0.0.0	VRage.Library.dll
2018-08-25T09:18:07.4426499-07:00	562,736	1.0.0.0	VRage.Math.dll
2018-08-25T09:18:09.3957617-07:00	190,512	VRage.Native.dll
2018-08-25T09:18:09.3957617-07:00	105,008	1.0.0.0	VRage.OpenVRWrapper.dll
2018-08-25T09:18:07.4426499-07:00	351,280	1.0.0.0	VRage.Render.dll
2018-08-25T09:18:07.4426499-07:00	983,088	1.0.0.0	VRage.Render11.dll
2018-03-27T14:51:20.0000000-07:00	77,824	3.0.1.0	WPFLocalizeExtension.dll
2018-01-08T19:35:48.0000000-08:00	27,648	1.2.2	XAMLMarkupExtensions.dll
System.MissingFieldException: Field not found: 'Sandbox.Game.Entities.MyVoxelBase.m_storage'.
at SEToolbox.Interop.Asteroids.MyVoxelMap.Load(String filename)
at SEToolbox.Models.StructurePlanetModel.ReadVoxelDetails(String filename) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructurePlanetModel.cs:line 358
at SEToolbox.Models.StructurePlanetModel..ctor(MyObjectBuilder_EntityBase entityBase, String voxelPath) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructurePlanetModel.cs:line 61
at SEToolbox.Models.StructureBaseModel.Create(MyObjectBuilder_EntityBase entityBase, String savefilePath) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructureBaseModel.cs:line 385
at SEToolbox.Models.ExplorerModel.LoadSectorDetail() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\ExplorerModel.cs:line 456
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by midspace** [comment]
Please see the new release to fix this issue.
https://github.com/midspace/SEToolbox/releases/latest
