### ISSUE TITLE
Custom Planet Regenerate Crash - Voxel Load Error?

### ISSUE THREAD

**Issue by DegenerateGroundState** [midspace/SEToolbox#150]
- [x] Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.
- [ ] Ensure that the issue is reproducible for testing. You may be requested to provide a link to a test world if we cannot reproduce it with your information.
- [x] Retrieve the Event Log from when SEToolbox crashed. Read the following [instructions](https://github.com/midspace/SEToolbox/wiki/Reporting-bugs) on retrieving the event log.

**SEToolbox Version:** 1.187.204.2
**SE Version:** 1.188.023

### SEToolbox crashed
Attempting to regenerate a custom planet

### Steps to Reproduce
When I attempt to regenerate planets, SEToolbox crashes.
However, this does not apply to EVERY planet, it seems to only apply to custom planets. I can regenerate the (vanilla) alien world in my save.

### SEToolbox Event Log
`2018-10-25 05:40:18,496 [1] WARN  SEToolbox.Support.DiagnosticsLogging [(null)] - The Space Engineers asteroid file 'C:\Users\REDACTED\AppData\Roaming\SpaceEngineers\Saves\76561197970160656\(Workshop) Full Solar System 7\RealMarsIRLGrav-1359378911d120000.vx2' could not be loaded, either because it is corrupt, or it is newer than expected.
System.Exception: Cannot load planet generator definition for subtype 'RealMarsIRLGrav'.
   at Sandbox.Engine.Voxels.MyPlanetStorageProvider.ReadFrom(Int32 storageVersion, Stream stream, Int32 size, Boolean& isOldFormat)
   at Sandbox.Engine.Voxels.MyOctreeStorage.ReadDataProvider(Stream stream, ChunkHeader header, Boolean& isOldFormat, IMyStorageDataProvider& provider)
   at Sandbox.Engine.Voxels.MyOctreeStorage.LoadInternal(Int32 fileVersion, Stream stream, Boolean& isOldFormat)
   at Sandbox.Engine.Voxels.MyStorageBase.Load(Stream stream, MyStorageBase& storage, Boolean& isOldFormat)
   at Sandbox.Engine.Voxels.MyStorageBase.Load(Byte[] memoryBuffer, String fileName)
   at Sandbox.Engine.Voxels.MyStorageBase.LoadFromFile(String absoluteFilePath, Dictionary`2 modifiers, Boolean cache)
   at SEToolbox.Interop.Asteroids.MyVoxelMap.Load(String filename) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\Asteroids\MyVoxelMap.cs:line 195
`
`2018-10-25 05:40:27,267 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" /B /B
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Bin64
SEBinVersion: 1.188.23
ProcessorCount: 4
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-US
CurrentCulture: 
Times started total: 16
Times started since last reset: 16
Times started since game update: 16

Files:
2018-10-24T11:47:45.6867814-04:00	25,057,840		HavokWrapper.dll
2017-06-02T08:49:12.0000000-04:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2017-03-08T18:26:22.0000000-05:00	276,480	2.0.8.0	log4net.dll
2018-10-23T01:39:25.3455977-04:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2018-10-23T01:39:25.3465962-04:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2018-09-09T01:31:30.0000000-04:00	911,360	0.32.0.0	Octokit.dll
2018-10-24T11:47:46.4548546-04:00	75,824	1.0.0.0	Sandbox.Common.dll
2018-10-24T11:47:45.6912731-04:00	7,370,288	1.0.0.0	Sandbox.Game.dll
2018-10-24T11:47:45.6917722-04:00	394,800	1.0.0.0	Sandbox.Graphics.dll
2018-10-24T11:47:48.0843281-04:00	18,480	1.0.0.0	Sandbox.RenderDirect.dll
2018-10-20T09:21:50.0000000-04:00	1,323,008	01.187.204.2	SEToolbox.exe
2017-06-02T08:49:12.0000000-04:00	745		SEToolbox.exe.config
2018-10-20T09:21:44.0000000-04:00	62,464	1.0.0.0	SEToolbox.ImageLibrary.dll
2018-10-20T09:21:44.0000000-04:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2018-10-20T09:21:50.0000000-04:00	2,248,192		SEToolbox.pdb
2018-10-20T09:21:44.0000000-04:00	53,248	1.0.0.0	SEToolboxUpdate.exe
2018-10-24T11:47:45.6942674-04:00	489,008	3.1.0	SharpDX.Direct2D1.dll
2018-10-24T11:47:45.6947665-04:00	288,304	3.1.0	SharpDX.Direct3D11.dll
2018-10-24T11:47:45.6962639-04:00	269,872	3.1.0	SharpDX.dll
2018-10-24T11:47:48.0878216-04:00	139,824	3.1.0	SharpDX.DXGI.dll
2018-10-24T11:47:45.6972621-04:00	456,240	1.0.0.0	SpaceEngineers.Game.dll
2018-10-24T11:47:48.1821466-04:00	60,464	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2018-10-24T11:47:45.6977612-04:00	4,559,408	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2018-10-24T11:47:45.6987591-04:00	329,264	11.0.0	Steamworks.NET.dll
2018-10-23T01:39:54.1707513-04:00	250,656	04.28.51.07	steam_api64.dll
2018-10-24T11:47:45.6992582-04:00	323,632	1.0.102.0	System.Data.SQLite.dll
2013-03-09T17:25:10.0000000-05:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2018-10-24T11:47:48.1911299-04:00	24,112	1.0.0.0	VRage.Ansel.dll
2018-10-24T11:47:48.1931264-04:00	68,656	1.0.0.0	VRage.Audio.dll
2018-10-24T11:47:45.6997573-04:00	497,712	1.0.0.0	VRage.dll
2018-10-24T11:47:45.7002564-04:00	1,318,448	1.0.0.0	VRage.Game.dll
2018-10-24T11:47:45.7012550-04:00	7,095,344	1.0.0.0	VRage.Game.XmlSerializers.dll
2018-10-24T11:47:48.2021095-04:00	98,864	1.0.0.0	VRage.Input.dll
2018-10-24T11:47:45.7017535-04:00	726,576	1.0.0.0	VRage.Library.dll
2018-10-24T11:47:45.7027517-04:00	562,736	1.0.0.0	VRage.Math.dll
2018-10-24T11:47:48.3253817-04:00	190,512		VRage.Native.dll
2018-10-24T11:47:48.3578203-04:00	105,008	1.0.0.0	VRage.OpenVRWrapper.dll
2018-10-24T11:47:45.7032508-04:00	355,888	1.0.0.0	VRage.Render.dll
2018-10-24T11:47:45.7042487-04:00	1,002,544	1.0.0.0	VRage.Render11.dll
2018-03-27T15:51:20.0000000-04:00	77,824	3.0.1.0	WPFLocalizeExtension.dll
2018-01-08T20:35:48.0000000-05:00	27,648	1.2.2	XAMLMarkupExtensions.dll

System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Engine.Voxels.MyPlanetStorageProvider.Init(Int64 seed)
   at Sandbox.Engine.Voxels.MyPlanetStorageProvider.Init(Int64 seed, MyPlanetGeneratorDefinition generator, Double radius)
   at SEToolbox.Models.StructurePlanetModel.RegeneratePlanet(Int32 seed, Single radius) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructurePlanetModel.cs:line 385
   at SEToolbox.ViewModels.StructurePlanetViewModel.RegenerateExecuted() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\StructurePlanetViewModel.cs:line 185
   at SEToolbox.Services.DelegateCommand.Execute() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 72
   at SEToolbox.Services.DelegateCommand.System.Windows.Input.ICommand.Execute(Object parameter) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 154
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by midspace** [comment]
Can you provide a copy of your world?

**Comment by midspace** [comment]
It appears that due to the new changes in Space Engineers 1.188 in how it handles mods, SEToolbox can no longer load them.

I can't fix this currently until I get some feedback from KeenSWH.

**Comment by Robot-Gentleman** [comment]
As a workaround if you extract the contents of the mod from steamapps/workshop/content/244850/[mod id]_legacy.bin into a folder in the old mods folder in roaming, then load the world with the local mod loaded instead of the workshop one you can regenerate the planet.

**Comment by Jakaya0897** [comment]
I've used the work around a couple of times but some planets cause errors using this method 

https://steamcommunity.com/sharedfiles/filedetails/?id=722041986

**Comment by midspace** [comment]
Refer to #152 for more details about the issue.
