### ISSUE TITLE
NullReferenceException Mirroring Modded Ship

### ISSUE THREAD

**Issue by Agentomega** [midspace/SEToolbox#151]
**SEToolbox Version:** 1.187.204.2
**SE Version:** 1.188.105

### SEToolbox crashed
What were you doing with SEToolbox when it happened?
Attempting to mirror a (modded) ship section.

### Steps to Reproduce
1. Import attached world.
2. Select ship named JIAN Strelitzia Nicolai with dimensions of 14x6x9 or 15x6x10.
3. Mirror Using Predefined X/Y/Z Planes.
[Omega Aerospace Shipyards.zip](https://github.com/midspace/SEToolbox/files/2752611/Omega.Aerospace.Shipyards.zip)

### SEToolbox Event Log
```
2019-01-12 17:37:35,801 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: M:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64
SEBinVersion: 1.188.105
ProcessorCount: 12
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-US
CurrentCulture: 
Times started total: 2
Times started since last reset: 2
Times started since game update: 2

Files:
2018-12-15T12:07:20.4679630-05:00	25,057,840		HavokWrapper.dll
2017-06-02T09:49:12.0000000-04:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2017-03-08T19:26:22.0000000-05:00	276,480	2.0.8.0	log4net.dll
2015-08-05T19:44:11.5621147-04:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2015-08-05T19:44:04.0404791-04:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2018-09-09T02:31:30.0000000-04:00	911,360	0.32.0.0	Octokit.dll
2018-12-15T12:07:25.7707295-05:00	75,824	1.0.0.0	Sandbox.Common.dll
2018-12-15T12:07:20.5563210-05:00	7,379,504	1.0.0.0	Sandbox.Game.dll
2018-12-15T12:07:20.5918759-05:00	395,824	1.0.0.0	Sandbox.Graphics.dll
2018-12-15T12:07:25.7797131-05:00	20,016	1.0.0.0	Sandbox.RenderDirect.dll
2018-10-20T10:21:50.0000000-04:00	1,323,008	01.187.204.2	SEToolbox.exe
2017-06-02T09:49:12.0000000-04:00	745		SEToolbox.exe.config
2018-10-20T10:21:44.0000000-04:00	62,464	1.0.0.0	SEToolbox.ImageLibrary.dll
2018-10-20T10:21:44.0000000-04:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2018-10-20T10:21:50.0000000-04:00	2,248,192		SEToolbox.pdb
2018-10-20T10:21:44.0000000-04:00	53,248	1.0.0.0	SEToolboxUpdate.exe
2018-12-15T12:07:20.6114362-05:00	489,008	3.1.0	SharpDX.Direct2D1.dll
2018-12-15T12:07:20.6119215-05:00	288,304	3.1.0	SharpDX.Direct3D11.dll
2018-12-15T12:07:20.6129219-05:00	269,872	3.1.0	SharpDX.dll
2018-12-15T12:07:25.7933696-05:00	139,824	3.1.0	SharpDX.DXGI.dll
2018-12-15T12:07:20.6134295-05:00	456,752	1.0.0.0	SpaceEngineers.Game.dll
2018-12-15T12:07:25.7972608-05:00	60,464	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2018-12-15T12:07:20.6284076-05:00	4,559,408	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2018-12-15T12:07:20.6288948-05:00	329,264	11.0.0	Steamworks.NET.dll
2018-07-22T14:16:12.4366079-04:00	250,656	04.28.51.07	steam_api64.dll
2018-12-15T12:07:20.6403893-05:00	323,632	1.0.102.0	System.Data.SQLite.dll
2013-03-09T18:25:10.0000000-05:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2018-12-15T12:07:25.7977619-05:00	24,112	1.0.0.0	VRage.Ansel.dll
2018-12-15T12:07:25.7992858-05:00	68,656	1.0.0.0	VRage.Audio.dll
2018-12-15T12:07:20.6418872-05:00	497,712	1.0.0.0	VRage.dll
2018-12-15T12:07:20.6423728-05:00	1,321,520	1.0.0.0	VRage.Game.dll
2018-12-15T12:07:20.6428721-05:00	7,095,344	1.0.0.0	VRage.Game.XmlSerializers.dll
2018-12-15T12:07:25.8002863-05:00	98,864	1.0.0.0	VRage.Input.dll
2018-12-15T12:07:20.6433850-05:00	727,088	1.0.0.0	VRage.Library.dll
2018-12-15T12:07:20.6438703-05:00	563,248	1.0.0.0	VRage.Math.dll
2018-12-15T12:07:26.8771305-05:00	190,512		VRage.Native.dll
2018-12-15T12:07:26.9070468-05:00	105,008	1.0.0.0	VRage.OpenVRWrapper.dll
2018-12-15T12:07:20.6438703-05:00	355,888	1.0.0.0	VRage.Render.dll
2018-12-15T12:07:20.6443699-05:00	1,004,080	1.0.0.0	VRage.Render11.dll
2018-03-27T16:51:20.0000000-04:00	77,824	3.0.1.0	WPFLocalizeExtension.dll
2018-01-08T21:35:48.0000000-05:00	27,648	1.2.2	XAMLMarkupExtensions.dll

System.NullReferenceException: Object reference not set to an instance of an object.
   at SEToolbox.Models.StructureCubeGridModel.MirrorCubeOrientation(MyCubeBlockDefinition definition, SerializableBlockOrientation orientation, Mirror xMirror, Mirror yMirror, Mirror zMirror, MyCubeBlockDefinition& mirrorDefinition, SerializableBlockOrientation& mirrorOrientation) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructureCubeGridModel.cs:line 1229
   at SEToolbox.Models.StructureCubeGridModel.MirrorCubes(StructureCubeGridModel viewModel, Boolean integrate, Mirror xMirror, Int32 xAxis, Mirror yMirror, Int32 yAxis, Mirror zMirror, Int32 zAxis) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructureCubeGridModel.cs:line 1193
   at SEToolbox.Models.StructureCubeGridModel.MirrorModel(Boolean usePlane, Boolean oddMirror) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructureCubeGridModel.cs:line 1155
   at SEToolbox.ViewModels.StructureCubeGridViewModel.MirrorStructureByPlaneExecuted() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\StructureCubeGridViewModel.cs:line 838
   at SEToolbox.Services.DelegateCommand.Execute() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 72
   at SEToolbox.Services.DelegateCommand.System.Windows.Input.ICommand.Execute(Object parameter) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 154
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by midspace** [comment]
This is due to the new Steam API inplmentation in SE.
