### ISSUE TITLE
Crash when resizing modded planet

### ISSUE THREAD

**Issue by NorthyPark** [midspace/SEToolbox#158]
- [x] Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.
- [x] Ensure that the issue is reproducible for testing. You may be requested to provide a link to a test world if we cannot reproduce it with your information.
- [x] Retrieve the Event Log from when SEToolbox crashed. Read the following [instructions](https://github.com/midspace/SEToolbox/wiki/Reporting-bugs) on retrieving the event log.

**SEToolbox Version:** SEToolbox 01.189.33 Release 1
**SE Version:** 01.189.41

### SEToolbox crashed
Resized a modded planet with custom voxel / textures for trees. Will not crash for vanilla planets or modded planets that only use vanilla assets

### Steps to Reproduce
Just try to resize a modded planet with custom voxel / textures for trees. It will crash

### SEToolbox Event Log
`2019-03-10 15:33:59,431 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Bin64
SEBinVersion: 1.189.41
ProcessorCount: 6
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-GB
CurrentCulture: 
Times started total: 4
Times started since last reset: 4
Times started since game update: 3

Files:
2019-03-09T22:25:43.5686089+01:00	25,104,944		HavokWrapper.dll
2017-06-02T09:49:12.0000000+02:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2017-03-08T19:26:22.0000000+01:00	276,480	2.0.8.0	log4net.dll
2019-01-17T19:05:17.0459313+01:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2019-01-17T19:05:17.0459313+01:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2018-09-09T02:31:30.0000000+02:00	911,360	0.32.0.0	Octokit.dll
2019-03-09T22:25:49.8286016+01:00	78,384	1.0.0.0	Sandbox.Common.dll
2019-03-09T22:25:43.5915338+01:00	7,657,008	1.0.0.0	Sandbox.Game.dll
2019-03-09T22:25:43.5915338+01:00	422,960	1.0.0.0	Sandbox.Graphics.dll
2019-03-09T22:25:48.4199991+01:00	22,576	1.0.0.0	Sandbox.RenderDirect.dll
2019-03-01T06:56:52.0000000+01:00	1,323,008	01.189.33.1	SEToolbox.exe
2017-06-02T09:49:12.0000000+02:00	745		SEToolbox.exe.config
2019-03-01T06:56:48.0000000+01:00	62,464	1.0.0.0	SEToolbox.ImageLibrary.dll
2019-03-01T06:56:48.0000000+01:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2019-03-01T06:56:52.0000000+01:00	2,248,192		SEToolbox.pdb
2019-03-01T06:56:48.0000000+01:00	53,248	1.0.0.0	SEToolboxUpdate.exe
2019-03-09T22:25:43.5915338+01:00	489,008	3.1.0	SharpDX.Direct2D1.dll
2019-03-09T22:25:43.5925310+01:00	288,304	3.1.0	SharpDX.Direct3D11.dll
2019-03-09T22:25:43.5925310+01:00	269,872	3.1.0	SharpDX.dll
2019-03-09T22:25:49.2342932+01:00	139,824	3.1.0	SharpDX.DXGI.dll
2019-03-09T22:25:43.5935287+01:00	499,248	1.0.0.0	SpaceEngineers.Game.dll
2019-03-09T22:25:47.9446835+01:00	63,536	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2019-03-09T22:25:43.5935287+01:00	4,847,664	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2019-03-09T22:25:43.5935287+01:00	329,264	11.0.0	Steamworks.NET.dll
2019-01-17T19:11:11.7507959+01:00	250,656	04.28.51.07	steam_api64.dll
2019-03-09T22:25:43.5935287+01:00	323,632	1.0.102.0	System.Data.SQLite.dll
2013-03-09T18:25:10.0000000+01:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2019-03-09T22:25:50.1274121+01:00	24,112	1.0.0.0	VRage.Ansel.dll
2019-03-09T22:25:50.8713497+01:00	68,656	1.0.0.0	VRage.Audio.dll
2019-03-09T22:25:43.5945257+01:00	501,296	1.0.0.0	VRage.dll
2019-03-09T22:25:43.5945257+01:00	1,377,840	1.0.0.0	VRage.Game.dll
2019-03-09T22:25:43.5945257+01:00	7,290,416	1.0.0.0	VRage.Game.XmlSerializers.dll
2019-03-09T22:25:50.1772965+01:00	98,864	1.0.0.0	VRage.Input.dll
2019-03-09T22:25:43.5945257+01:00	732,208	1.0.0.0	VRage.Library.dll
2019-03-09T22:25:43.5955230+01:00	563,760	1.0.0.0	VRage.Math.dll
2019-03-09T22:25:51.2682617+01:00	207,408		VRage.Native.dll
2019-03-09T22:25:51.0197099+01:00	105,008	1.0.0.0	VRage.OpenVRWrapper.dll
2019-03-09T22:25:43.5955230+01:00	357,936	1.0.0.0	VRage.Render.dll
2019-03-09T22:25:43.5955230+01:00	982,064	1.0.0.0	VRage.Render11.dll
2018-03-27T16:51:20.0000000+02:00	77,824	3.0.1.0	WPFLocalizeExtension.dll
2018-01-08T21:35:48.0000000+01:00	27,648	1.2.2	XAMLMarkupExtensions.dll

System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Engine.Voxels.MyPlanetStorageProvider.Init(Int64 seed)
   at Sandbox.Engine.Voxels.MyPlanetStorageProvider.Init(Int64 seed, MyPlanetGeneratorDefinition generator, Double radius)
   at SEToolbox.Models.StructurePlanetModel.RegeneratePlanet(Int32 seed, Single radius) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructurePlanetModel.cs:line 385
   at SEToolbox.ViewModels.StructurePlanetViewModel.RegenerateExecuted() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\StructurePlanetViewModel.cs:line 185
   at SEToolbox.Services.DelegateCommand.Execute() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 72
   at SEToolbox.Services.DelegateCommand.System.Windows.Input.ICommand.Execute(Object parameter) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 154
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by midspace** [comment]
This is an issue with loading mods. See #152

**Comment by shadow7483147** [comment]
Currently you can unpack the modded planet's Generator Definitions from the workshop content folder, into your Space Engineers data folder in your Steam library, as a workaround.
