### ISSUE TITLE
Not working with Space Engineers update 1.191.023 (2 days ago)

### ISSUE THREAD

**Issue by marshalleq** [midspace/SEToolbox#171]
- [ ] Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.
- [ ] Ensure that the issue is reproducible for testing. You may be requested to provide a link to a test world if we cannot reproduce it with your information.
- [ ] Retrieve the Event Log from when SEToolbox crashed. Read the following [instructions](https://github.com/midspace/SEToolbox/wiki/Reporting-bugs) on retrieving the event log.

**SEToolbox Version:** 1.191.20.1
**SE Version:** 1.191.023

### Steps to Reproduce
1. Post install of SE toolbox, select the SE Dedicated server application in Torch
2. Error message received that 'invalid location specified

The full path is C:\torchserver\DedicatedServer64\SpaceEngineersDedicated.exe

### SEToolbox Event Log - doesn't exist as can't start and is new install
```
Paste your event log here.
```

**Comment by midspace** [comment]
It appears Keen have dropped two files from the Space Engineers Dedicated installation.
`msvcp120.dll`
`msvcr120.dll`

If you can copy those from the game install to the SEToolbox installed path, that should get it working.
Frankly speaking, those files should be installed into Windows when you install the game, so they shouldn't be distributed with the game. I'm not sure if they are installed with the Dedicated Server however, which does present more of an issue, as the server doesn't "install" like the game does.

**Comment by Matorx** [comment]
my problem is: 2019-06-09 21:33:35,904 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: E:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64
SEBinVersion: 1.191.23
ProcessorCount: 8
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: True
CurrentUICulture: cs-CZ
CurrentCulture: 
Times started total: 253
Times started since last reset: 253
Times started since game update: 5

Files:
2019-06-08T06:44:13.2017460+02:00	252,600	0.1.1	HavokWrapper.dll
2017-06-02T07:49:12.0000000+02:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2017-03-08T17:26:22.0000000+01:00	276,480	2.0.8.0	log4net.dll
2018-10-10T19:15:45.3387922+02:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2018-10-10T19:15:45.3397747+02:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2019-06-06T19:31:29.5102881+02:00	98,616	4.6.26011.1	netstandard.dll
2018-09-09T00:31:30.0000000+02:00	911,360	0.32.0.0	Octokit.dll
2019-06-08T06:44:11.9077974+02:00	281,784	2.4.0.8641	protobuf-net.dll
2019-06-08T06:44:13.5198928+02:00	73,400	1.0.0.0	Sandbox.Common.dll
2019-06-08T06:44:11.9118158+02:00	7,455,928	0.1.1	Sandbox.Game.dll
2019-06-08T06:44:13.5478975+02:00	94,904	0.1.1.0	Sandbox.Game.XmlSerializers.dll
2019-06-08T06:44:11.9118158+02:00	383,160	0.1.1	Sandbox.Graphics.dll
2019-06-08T06:44:13.5758934+02:00	20,152	1.0.0.0	Sandbox.RenderDirect.dll
2019-06-07T07:10:24.0000000+02:00	1,327,104	01.191.20.1	SEToolbox.exe
2017-06-02T07:49:12.0000000+02:00	745		SEToolbox.exe.config
2019-06-07T06:54:38.0000000+02:00	62,464	1.0.0.0	SEToolbox.ImageLibrary.dll
2019-06-07T07:10:20.0000000+02:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2019-06-07T07:10:24.0000000+02:00	2,262,528		SEToolbox.pdb
2019-06-07T07:10:20.0000000+02:00	53,760	1.0.0.0	SEToolboxUpdate.exe
2019-06-08T06:44:11.9118158+02:00	501,944	4.2.0	SharpDX.Direct2D1.dll
2019-06-08T06:44:11.9158243+02:00	289,464	4.2.0	SharpDX.Direct3D11.dll
2019-06-08T06:44:11.9158243+02:00	281,272	4.2.0	SharpDX.dll
2019-06-08T06:44:13.6969395+02:00	154,808	4.2.0	SharpDX.DXGI.dll
2019-06-08T06:44:11.9158243+02:00	488,120	1.0.0.0	SpaceEngineers.Game.dll
2019-06-08T06:44:13.7009374+02:00	61,624	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2019-06-08T06:44:11.9197977+02:00	5,079,224	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2019-06-08T06:44:11.9197977+02:00	327,864	11.0.0	Steamworks.NET.dll
2018-10-10T19:16:46.5522250+02:00	250,656	04.28.51.07	steam_api64.dll
2019-06-08T06:44:11.9197977+02:00	322,232	1.0.102.0	System.Data.SQLite.dll
2013-03-09T16:25:10.0000000+01:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2019-06-08T06:44:13.8090390+02:00	23,224	1.0.0.0	VRage.Ansel.dll
2019-06-08T06:44:13.8090390+02:00	65,208	1.0.0.0	VRage.Audio.dll
2019-06-08T06:44:11.9197977+02:00	486,072	1.0.0.0	VRage.dll
2019-06-08T06:44:11.9197977+02:00	1,359,032	1.0.0.0	VRage.Game.dll
2019-06-08T06:44:11.9237967+02:00	7,031,992	1.0.0.0	VRage.Game.XmlSerializers.dll
2019-06-08T06:44:13.8127766+02:00	48,824	1.0.0.0	VRage.Input.dll
2019-06-08T06:44:11.9237967+02:00	406,200	1.0.0.0	VRage.Library.dll
2019-06-08T06:44:11.9237967+02:00	543,928	1.0.0.0	VRage.Math.dll
2019-06-08T06:44:13.8371786+02:00	101,048		VRage.Native.dll
2019-06-08T06:44:13.8411824+02:00	23,224	0.1.1	VRage.NativeWrapper.dll
2019-06-08T06:44:11.9237967+02:00	342,200	1.0.0.0	VRage.Render.dll
2019-06-08T06:44:11.9237967+02:00	920,248	1.0.0.0	VRage.Render11.dll
2018-03-27T14:51:20.0000000+02:00	77,824	3.0.1.0	WPFLocalizeExtension.dll
2018-01-08T19:35:48.0000000+01:00	27,648	1.2.2	XAMLMarkupExtensions.dll

System.IO.FileNotFoundException: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Sandbox.Game.World.Generator.MyCompositeShapes.CombinedGenerator(Int32 version, Int32 seed, Single size)
   at Sandbox.Game.World.Generator.MyCompositeShapes.<>c__DisplayClass4_0.<.cctor>b__3(Int32 generatorSeed, Int32 seed, Single size)
   at Sandbox.Game.World.Generator.MyCompositeShapeProvider.InitFromState(State state)
   at Sandbox.Game.World.Generator.MyCompositeShapeProvider.VRage.Voxels.IMyStorageDataProvider.ReadFrom(Int32 storageVersion, Stream stream, Int32 size, Boolean& isOldFormat)
   at Sandbox.Engine.Voxels.MyOctreeStorage.ReadDataProvider(Stream stream, ChunkHeader header, Boolean& isOldFormat, IMyStorageDataProvider& provider)
   at Sandbox.Engine.Voxels.MyOctreeStorage.LoadInternal(Int32 fileVersion, Stream stream, Boolean& isOldFormat)
   at Sandbox.Engine.Voxels.MyStorageBase.Load(Stream stream, MyStorageBase& storage, Boolean& isOldFormat)
   at Sandbox.Engine.Voxels.MyStorageBase.Load(Byte[] memoryBuffer)
   at Sandbox.Engine.Voxels.MyStorageBase.LoadFromFile(String absoluteFilePath, Dictionary`2 modifiers, Boolean cache)
   at SEToolbox.Interop.Asteroids.MyVoxelMap.Load(String filename) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\Asteroids\MyVoxelMap.cs:line 202
   at SEToolbox.Models.StructureVoxelModel.ReadVoxelDetails(String filename) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructureVoxelModel.cs:line 359
   at SEToolbox.Models.StructureVoxelModel..ctor(MyObjectBuilder_EntityBase entityBase, String voxelPath) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructureVoxelModel.cs:line 78
   at SEToolbox.Models.StructureBaseModel.Create(MyObjectBuilder_EntityBase entityBase, String savefilePath) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructureBaseModel.cs:line 390
   at SEToolbox.Models.ExplorerModel.LoadSectorDetail() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\ExplorerModel.cs:line 456
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by midspace** [comment]
Please download the [latest release](https://github.com/midspace/SEToolbox/releases/latest) for a fix to this issue.
