### ISSUE TITLE
Unable to export blueprint from saved world

### ISSUE THREAD

**Issue by Kaipherion** [midspace/SEToolbox#172]
### Unable to export blueprint from saved world

**SEToolbox Version:** 01.191.20.1-en
**SE Version:** 1.191.023

### SEToolbox crashed
![error message, small (2019-06-10)](https://user-images.githubusercontent.com/51678070/59220576-53915e80-8b93-11e9-93e7-d11cd93e6d6a.JPG)

**What were you doing with SEToolbox when it happened?**
I was trying to export a small grid ship as a blueprint.

### Steps to Reproduce
1. I opened an existing world that has no mods.
2. When I try to export file as a blueprint, I get the error (image attached) and the the application closes immediately.
3. I have tried to export a grid as a 'blueprint' from several saved files (with and without mods), with the same result.
4. I have tried to export a grid as a 'prefab' from several save files (with and without mods), with the same result.

### SEToolbox Event Log 
(from save game with no mods)
```
2019-06-10 15:04:50,545 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: E:\All Game Tools, Apps, & Utilities\SEToolbox\SEToolbox.exe
CommandLine: "E:\All Game Tools, Apps, & Utilities\SEToolbox\SEToolbox.exe" 
CurrentDirectory: E:\All Game Tools, Apps, & Utilities\SEToolbox
SEBinPath: E:\Steam\SteamApps\common\SpaceEngineers\Bin64
SEBinVersion: 1.191.23
ProcessorCount: 12
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: True
CurrentUICulture: en-US
CurrentCulture: 
Times started total: 3
Times started since last reset: 3
Times started since game update: 3

Files:
2019-06-07T19:10:12.8270758-04:00	252,600	0.1.1	HavokWrapper.dll
2017-06-01T17:49:11.8637547-04:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2017-03-08T03:26:22.0000000-05:00	276,480	2.0.8.0	log4net.dll
2017-11-08T20:46:10.5516687-05:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2017-11-08T20:46:10.5516687-05:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2019-06-06T13:31:52.1136474-04:00	98,616	4.6.26011.1	netstandard.dll
2018-09-08T10:31:30.0000000-04:00	911,360	0.32.0.0	Octokit.dll
2019-06-07T19:10:12.6820698-04:00	281,784	2.4.0.8641	protobuf-net.dll
2019-06-07T19:10:12.8330656-04:00	73,400	1.0.0.0	Sandbox.Common.dll
2019-06-07T19:10:12.6820698-04:00	7,455,928	0.1.1	Sandbox.Game.dll
2019-06-07T19:10:12.8460380-04:00	94,904	0.1.1.0	Sandbox.Game.XmlSerializers.dll
2019-06-07T19:10:12.6831151-04:00	383,160	0.1.1	Sandbox.Graphics.dll
2019-06-07T19:10:12.8460380-04:00	20,152	1.0.0.0	Sandbox.RenderDirect.dll
2019-06-06T17:10:23.4140668-04:00	1,327,104	01.191.20.1	SEToolbox.exe
2017-06-01T17:49:11.8907658-04:00	745		SEToolbox.exe.config
2019-06-06T16:54:36.4696279-04:00	62,464	1.0.0.0	SEToolbox.ImageLibrary.dll
2019-06-06T17:10:19.4852843-04:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2019-06-06T17:10:23.4140668-04:00	2,262,528		SEToolbox.pdb
2019-06-06T17:10:18.9439093-04:00	53,760	1.0.0.0	SEToolboxUpdate.exe
2019-06-07T19:10:12.6831151-04:00	501,944	4.2.0	SharpDX.Direct2D1.dll
2019-06-07T19:10:12.6831151-04:00	289,464	4.2.0	SharpDX.Direct3D11.dll
2019-06-07T19:10:12.6840959-04:00	281,272	4.2.0	SharpDX.dll
2019-06-07T19:10:12.8469982-04:00	154,808	4.2.0	SharpDX.DXGI.dll
2019-06-07T19:10:12.6850940-04:00	488,120	1.0.0.0	SpaceEngineers.Game.dll
2019-06-07T19:10:12.8499896-04:00	61,624	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2019-06-07T19:10:12.6860592-04:00	5,079,224	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2019-06-07T19:10:12.6860592-04:00	327,864	11.0.0	Steamworks.NET.dll
2018-07-19T13:22:22.0975235-04:00	250,656	04.28.51.07	steam_api64.dll
2019-06-07T19:10:12.6860592-04:00	322,232	1.0.102.0	System.Data.SQLite.dll
2013-03-09T02:25:10.0000000-05:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2019-06-07T19:10:12.8519846-04:00	23,224	1.0.0.0	VRage.Ansel.dll
2019-06-07T19:10:12.8519846-04:00	65,208	1.0.0.0	VRage.Audio.dll
2019-06-07T19:10:12.6870565-04:00	486,072	1.0.0.0	VRage.dll
2019-06-07T19:10:12.6870565-04:00	1,359,032	1.0.0.0	VRage.Game.dll
2019-06-07T19:10:12.6880539-04:00	7,031,992	1.0.0.0	VRage.Game.XmlSerializers.dll
2019-06-07T19:10:12.8559743-04:00	48,824	1.0.0.0	VRage.Input.dll
2019-06-07T19:10:12.6880539-04:00	406,200	1.0.0.0	VRage.Library.dll
2019-06-07T19:10:12.6880539-04:00	543,928	1.0.0.0	VRage.Math.dll
2019-06-07T19:10:12.8579687-04:00	101,048		VRage.Native.dll
2019-06-07T19:10:13.0844469-04:00	23,224	0.1.1	VRage.NativeWrapper.dll
2019-06-07T19:10:12.6890517-04:00	342,200	1.0.0.0	VRage.Render.dll
2019-06-07T19:10:12.6890517-04:00	920,248	1.0.0.0	VRage.Render11.dll
2018-03-27T00:51:20.0000000-04:00	77,824	3.0.1.0	WPFLocalizeExtension.dll
2018-01-08T05:35:48.0000000-05:00	27,648	1.2.2	XAMLMarkupExtensions.dll

System.InvalidOperationException: Unexpected sub-type: Sandbox.Common.ObjectBuilders.MyObjectBuilder_Wheel
   at ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(Type expected, Type actual)
   at ProtoBuf.Serializers.TypeSerializer.GetMoreSpecificSerializer(Object value)
   at ProtoBuf.Serializers.TypeSerializer.Callback(Object value, CallbackType callbackType, SerializationContext context)
   at ProtoBuf.Serializers.TagDecorator.Callback(Object value, CallbackType callbackType, SerializationContext context)
   at ProtoBuf.Serializers.TypeSerializer.Callback(Object value, CallbackType callbackType, SerializationContext context)
   at ProtoBuf.Serializers.TypeSerializer.Write(Object value, ProtoWriter dest)
   at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer)
   at proto_348(Object , ProtoWriter )
   at ProtoBuf.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at proto_338(Object , ProtoWriter )
   at ProtoBuf.ProtoWriter.WriteRecursionSafeObject(Object value, Int32 key, ProtoWriter writer)
   at ProtoBuf.Serializers.TypeSerializer.Write(Object value, ProtoWriter dest)
   at ProtoBuf.Meta.TypeModel.SerializeCore(ProtoWriter writer, Object value)
   at ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value, SerializationContext context)
   at VRage.ObjectBuilders.MyObjectBuilderSerializer.Clone(MyObjectBuilder_Base toClone)
   at SEToolbox.ViewModels.ExplorerViewModel.ExportBlueprintToFile(IStructureViewBase[] viewModels) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\ExplorerViewModel.cs:line 1969
   at SEToolbox.ViewModels.ExplorerViewModel.ExportBlueprintExecuted() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\ExplorerViewModel.cs:line 764
   at SEToolbox.Services.DelegateCommand.Execute() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 72
   at SEToolbox.Services.DelegateCommand.System.Windows.Input.ICommand.Execute(Object parameter) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 154
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by midspace** [comment]
Seems to be a low level error from the Game code. I'm not sure how to resolve this currently.

**Comment by Kaipherion** [comment]
Thank you for looking into this for me. Seems like I'll just have to live
with it for now. Not a deal breaker, just an inconvenience, likely brought
on by coffee changes in the most recent Leander of SE. I honestly don't
know, since I'm not a programmer lol

I do appreciate all the effort and work you (and others like yourself) put
into these tools and projects, on our behalf.

Than you.


Keep up the great work!


Cheers!

**Comment by midspace** [comment]
Please download the [latest release](https://github.com/midspace/SEToolbox/releases/latest) for a fix to this issue.
