### ISSUE TITLE
Crash at start when offline

### ISSUE THREAD

**Issue by posthy** [midspace/SEToolbox#176]
**SEToolbox Version:** 01.191.20 Release 2
**SE Version:** 1.191.1

### SEToolbox crashed
Tried to launch SEToolbox after install from .msi

### Steps to Reproduce
1. Make internet inaccessible, go offline, or block SEToolbox on the firewall
2. Start SEToolbox

### SEToolbox Event Log
2019-06-20 13:27:56,443 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Tools\Toolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Tools\Toolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Tools\Toolbox
SEBinPath: 
SEBinVersion: 
ProcessorCount: 8
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-US
CurrentCulture: hu-HU
Times started total: 
Times started since last reset: 
Times started since game update: 

Files:
2017-06-01T23:49:11.8637547+02:00	498 176	2014.2.17.1	HelixToolkit.Wpf.dll
2017-03-08T09:26:22.0000000+01:00	276 480	2.0.8.0	log4net.dll
2018-09-08T16:31:30.0000000+02:00	911 360	0.32.0.0	Octokit.dll
2019-06-18T17:56:48.0000000+02:00	1 327 616	01.191.20.2	SEToolbox.exe
2017-06-01T23:49:11.8907658+02:00	745		SEToolbox.exe.config
2019-02-28T20:56:47.3352625+01:00	62 464	1.0.0.0	SEToolbox.ImageLibrary.dll
2019-02-28T20:56:47.6886315+01:00	7 680	1.0.0.0	SEToolbox.ImageShaders.dll
2019-02-28T20:56:51.3625238+01:00	2 248 192		SEToolbox.pdb
2019-02-28T20:56:46.7843096+01:00	53 248	1.0.0.0	SEToolboxUpdate.exe
2013-03-09T08:25:10.0000000+01:00	39 936	2.0.20525.0	System.Windows.Interactivity.dll
2018-03-27T06:51:20.0000000+02:00	77 824	3.0.1.0	WPFLocalizeExtension.dll
2018-01-08T11:35:48.0000000+01:00	27 648	1.2.2	XAMLMarkupExtensions.dll

System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 140.82.118.5:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Internal.HttpClientAdapter.<SendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Internal.HttpClientAdapter.<Send>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<RunRequest>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__8`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SEToolbox.Support.CodeRepositoryReleases.CheckForUpdates(Version currentVersion, Boolean dontIgnore)
   at SEToolbox.App.OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 140.82.118.5:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Internal.HttpClientAdapter.<SendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Internal.HttpClientAdapter.<Send>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<RunRequest>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__8`1.MoveNext()<---

**Comment by midspace** [comment]
@posthy 
What exactly do you do to go offline?
- [ ] Lose connection to ISP.
- [ ] Turn router or other network link device off?
- [ ] Turn wifi off on router or computer?
- [ ] Pull out cable from computer?
- [ ] Other (please describe).

**Comment by posthy** [comment]
Probably any of these would cause the error, but for me, I have the free version of Win 10 Firewall Control from [Sphinx software](https://www.sphinx-soft.com/) which allows windows' built-in firewall to regulate outgoing requests as well, not just inbuonds, and SEToolbox is blocked by default as unknown application.
