### ISSUE TITLE
1.125.1.1 Throwing Errors when creating astroids

### ISSUE THREAD

**Issue by worsin** [midspace/SEToolbox#55]
If i try to add astroids through the Generate Asteroid Field option i get an exception that closes down SEToolbox.

`2016-03-14 18:55:26,933 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64
SEBinVersion: 1.125.15
ProcessorCount: 4
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-US
CurrentCulture: en-US

Files:
2016-03-11T12:49:04.4677419-07:00	24,782,776		HavokWrapper.dll
2016-01-11T17:42:58.0000000-07:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2016-01-11T17:42:58.0000000-07:00	200,704	0.86.0.518	ICSharpCode.SharpZipLib.dll
2016-01-11T17:42:58.0000000-07:00	301,056	1.2.13.0	log4net.dll
2016-03-11T12:49:07.5032864-07:00	90,040	1.0.0.0	Sandbox.Common.dll
2016-03-11T12:49:07.8895947-07:00	5,471,672	1.0.0.0	Sandbox.Game.dll
2016-03-10T20:44:50.0000000-07:00	1,241,600	01.125.001.1	SEToolbox.exe
2016-01-12T16:41:58.0000000-07:00	747		SEToolbox.exe.config
2016-03-06T18:03:22.0000000-07:00	27,648	1.0.0.0	SEToolbox.ImageLibrary.dll
2016-03-10T20:44:44.0000000-07:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2016-03-10T20:44:50.0000000-07:00	2,354,688		SEToolbox.pdb
2016-03-10T20:44:44.0000000-07:00	51,200	1.0.0.0	SEToolboxUpdate.exe
2016-03-11T12:49:05.1496386-07:00	49,592	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2016-03-11T12:49:07.8398015-07:00	10,385,336	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2016-01-11T17:42:58.0000000-07:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2016-03-11T12:49:08.0664254-07:00	644,536	1.0.0.0	VRage.dll
2016-03-11T12:49:07.8649419-07:00	587,704	1.0.0.0	VRage.Game.dll
2016-03-11T12:49:07.9894163-07:00	2,358,200	1.0.0.0	VRage.Game.XmlSerializers.dll
2016-03-11T12:49:05.4782605-07:00	631,224	1.0.0.0	VRage.Library.dll
2016-03-11T12:49:03.2095948-07:00	470,456	1.0.0.0	VRage.Math.dll
2016-01-11T17:42:58.0000000-07:00	64,512	2.2.0	WPFLocalizeExtension.dll
2016-01-11T17:42:58.0000000-07:00	26,624	1.1.6.3	XAMLMarkupExtensions.dll

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SEToolbox.Models.Asteroids.AsteroidByteFiller.CreateRandom(Int32 index, MaterialSelectionModel defaultMaterial, IEnumerable`1 materialsCollection, IEnumerable`1 voxelCollection) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\Asteroids\AsteroidByteFiller.cs:line 153
   at SEToolbox.ViewModels.GenerateVoxelFieldViewModel.AddRandomRowExecuted() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\GenerateVoxelFieldViewModel.cs:line 212
   at SEToolbox.Services.DelegateCommand.Execute() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 72
   at SEToolbox.Services.DelegateCommand.System.Windows.Input.ICommand.Execute(Object parameter) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 154
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

This happens when i select to generate a random asteroid field.

If i add one and select all of the resources etc it does not throw the error, however when i load into game it gives me an error saying that it could not load 1 or more objects and the asteroids do not load.

**Comment by worsin** [comment]
Adding to this im finding the same error when trying to simply add single asteroids as well.

**Comment by midspace** [comment]
The "Add Random" button appears to be broken.


As for adding single asteroids, please see the following:
https://github.com/midspace/SEToolbox/wiki/Current-Issues

**Comment by midspace** [comment]
The fix will appear in the next release.

**Comment by midspace** [comment]
This has been released.
