### ISSUE TITLE
Can't update SE Toolbox, unable to locate file in SE bin

### ISSUE THREAD

**Issue by mtracy01** [midspace/SEToolbox#61]
Hi,  When I tried to update SE Toolbox I crashed after trying to update the tool.  I checked the application file, and it looks like the file 'VRage.Game.MyObjectBuilder_DefinitionBase.Icon' was missing in my Bin64.  I verified that the program paths are correct and that the file is not there.  Was this removed in the recent SE update and now causing the crash?  Or do I need to re-download some SE files (I don't see any way the file could've been missing by accident).

I have attached my event log below for your reference:

```
Log Name:      Application
Source:        SEToolbox.exe
Date:          3/31/2016 2:00:06 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Core-M
Description:
2016-03-31 14:00:06,517 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64
SEBinVersion: 1.128.7
ProcessorCount: 16
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: True
CurrentUICulture: en-US
CurrentCulture: en-US

Files:
2016-03-31T13:07:54.9161948-04:00	28,192,184		HavokWrapper.dll
2016-01-11T17:42:58.0000000-05:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2016-01-11T17:42:58.0000000-05:00	200,704	0.86.0.518	ICSharpCode.SharpZipLib.dll
2016-01-11T17:42:58.0000000-05:00	301,056	1.2.13.0	log4net.dll
2016-03-31T13:07:45.5694629-04:00	37,304	1.0.0.0	Sandbox.Common.dll
2016-03-31T13:07:56.2379257-04:00	5,420,472	1.0.0.0	Sandbox.Game.dll
2016-03-17T18:55:38.0000000-04:00	1,253,376	01.126.003.1	SEToolbox.exe
2016-01-12T16:41:58.0000000-05:00	747		SEToolbox.exe.config
2016-03-06T18:03:22.0000000-05:00	27,648	1.0.0.0	SEToolbox.ImageLibrary.dll
2016-03-17T18:55:28.0000000-04:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2016-03-17T18:55:38.0000000-04:00	2,373,120		SEToolbox.pdb
2016-03-10T20:44:44.0000000-05:00	51,200	1.0.0.0	SEToolboxUpdate.exe
2016-03-31T13:07:42.8521526-04:00	49,592	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2016-03-31T13:07:56.4271261-04:00	11,067,320	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2016-01-11T17:42:58.0000000-05:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2016-03-31T13:07:49.0858227-04:00	656,312	1.0.0.0	VRage.dll
2016-03-31T13:07:56.3025437-04:00	652,728	1.0.0.0	VRage.Game.dll
2016-03-31T13:07:47.8154582-04:00	2,484,664	1.0.0.0	VRage.Game.XmlSerializers.dll
2016-03-31T13:07:42.9245463-04:00	635,832	1.0.0.0	VRage.Library.dll
2016-03-31T13:07:56.5202011-04:00	470,456	1.0.0.0	VRage.Math.dll
2016-01-11T17:42:58.0000000-05:00	64,512	2.2.0	WPFLocalizeExtension.dll
2016-01-11T17:42:58.0000000-05:00	26,624	1.1.6.3	XAMLMarkupExtensions.dll

System.TypeInitializationException: The type initializer for 'SEToolbox.Interop.SpaceEngineersCore' threw an exception. ---> System.MissingFieldException: Field not found: 'VRage.Game.MyObjectBuilder_DefinitionBase.Icon'.
   at SEToolbox.Interop.SpaceEngineersResources.<LoadContent>b__57(MyObjectBuilder_AmmoMagazineDefinition magazine)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at SEToolbox.Interop.SpaceEngineersResources.LoadContent(String stockContentPath, String modContentPath, String zipModFile, String[] zipFiles, MyObjectBuilder_Definitions definitions, Dictionary`2& contentData) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersResources.cs:line 286
   at SEToolbox.Interop.SpaceEngineersResources.LoadAllDefinitions(String stockContentPath, String modContentPath, Dictionary`2& contentData) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersResources.cs:line 189
   at SEToolbox.Interop.SpaceEngineersResources.FindDefinitions(String contentPath, IEnumerable`1 modPaths, MyObjectBuilder_Definitions& definitions, Dictionary`2& contentData) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersResources.cs:line 106
   at SEToolbox.Interop.SpaceEngineersResources.ReadCubeBlockDefinitions(String contentPath, String[] modPaths) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersResources.cs:line 88
   at SEToolbox.Interop.SpaceEngineersResources.LoadDefinitions() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersResources.cs:line 34
   at SEToolbox.Interop.SpaceEngineersCore..ctor() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 40
   at SEToolbox.Interop.SpaceEngineersCore..cctor() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 17
   --- End of inner exception stack trace ---
   at SEToolbox.Interop.SpaceEngineersCore.LoadDefinitions()
   at SEToolbox.CoreToolbox.Load(String[] args) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\CoreToolbox.cs:line 181
   at SEToolbox.App.OnStartup(Object sender, StartupEventArgs e) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\App.xaml.cs:line 92
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="SEToolbox.exe" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-03-31T18:00:06.543883600Z" />
    <EventRecordID>813764</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Core-M</Computer>
    <Security />
  </System>
  <EventData>
    <Data>2016-03-31 14:00:06,517 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64
SEBinVersion: 1.128.7
ProcessorCount: 16
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: True
CurrentUICulture: en-US
CurrentCulture: en-US

Files:
2016-03-31T13:07:54.9161948-04:00	28,192,184		HavokWrapper.dll
2016-01-11T17:42:58.0000000-05:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2016-01-11T17:42:58.0000000-05:00	200,704	0.86.0.518	ICSharpCode.SharpZipLib.dll
2016-01-11T17:42:58.0000000-05:00	301,056	1.2.13.0	log4net.dll
2016-03-31T13:07:45.5694629-04:00	37,304	1.0.0.0	Sandbox.Common.dll
2016-03-31T13:07:56.2379257-04:00	5,420,472	1.0.0.0	Sandbox.Game.dll
2016-03-17T18:55:38.0000000-04:00	1,253,376	01.126.003.1	SEToolbox.exe
2016-01-12T16:41:58.0000000-05:00	747		SEToolbox.exe.config
2016-03-06T18:03:22.0000000-05:00	27,648	1.0.0.0	SEToolbox.ImageLibrary.dll
2016-03-17T18:55:28.0000000-04:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2016-03-17T18:55:38.0000000-04:00	2,373,120		SEToolbox.pdb
2016-03-10T20:44:44.0000000-05:00	51,200	1.0.0.0	SEToolboxUpdate.exe
2016-03-31T13:07:42.8521526-04:00	49,592	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2016-03-31T13:07:56.4271261-04:00	11,067,320	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2016-01-11T17:42:58.0000000-05:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2016-03-31T13:07:49.0858227-04:00	656,312	1.0.0.0	VRage.dll
2016-03-31T13:07:56.3025437-04:00	652,728	1.0.0.0	VRage.Game.dll
2016-03-31T13:07:47.8154582-04:00	2,484,664	1.0.0.0	VRage.Game.XmlSerializers.dll
2016-03-31T13:07:42.9245463-04:00	635,832	1.0.0.0	VRage.Library.dll
2016-03-31T13:07:56.5202011-04:00	470,456	1.0.0.0	VRage.Math.dll
2016-01-11T17:42:58.0000000-05:00	64,512	2.2.0	WPFLocalizeExtension.dll
2016-01-11T17:42:58.0000000-05:00	26,624	1.1.6.3	XAMLMarkupExtensions.dll

System.TypeInitializationException: The type initializer for 'SEToolbox.Interop.SpaceEngineersCore' threw an exception. ---&gt; System.MissingFieldException: Field not found: 'VRage.Game.MyObjectBuilder_DefinitionBase.Icon'.
   at SEToolbox.Interop.SpaceEngineersResources.&lt;LoadContent&gt;b__57(MyObjectBuilder_AmmoMagazineDefinition magazine)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at SEToolbox.Interop.SpaceEngineersResources.LoadContent(String stockContentPath, String modContentPath, String zipModFile, String[] zipFiles, MyObjectBuilder_Definitions definitions, Dictionary`2&amp; contentData) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersResources.cs:line 286
   at SEToolbox.Interop.SpaceEngineersResources.LoadAllDefinitions(String stockContentPath, String modContentPath, Dictionary`2&amp; contentData) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersResources.cs:line 189
   at SEToolbox.Interop.SpaceEngineersResources.FindDefinitions(String contentPath, IEnumerable`1 modPaths, MyObjectBuilder_Definitions&amp; definitions, Dictionary`2&amp; contentData) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersResources.cs:line 106
   at SEToolbox.Interop.SpaceEngineersResources.ReadCubeBlockDefinitions(String contentPath, String[] modPaths) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersResources.cs:line 88
   at SEToolbox.Interop.SpaceEngineersResources.LoadDefinitions() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersResources.cs:line 34
   at SEToolbox.Interop.SpaceEngineersCore..ctor() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 40
   at SEToolbox.Interop.SpaceEngineersCore..cctor() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 17
   --- End of inner exception stack trace ---
   at SEToolbox.Interop.SpaceEngineersCore.LoadDefinitions()
   at SEToolbox.CoreToolbox.Load(String[] args) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\CoreToolbox.cs:line 181
   at SEToolbox.App.OnStartup(Object sender, StartupEventArgs e) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\App.xaml.cs:line 92
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.&lt;.ctor&gt;b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
</Data>
  </EventData>
</Event>
```

**Comment by midspace** [comment]
I did warn all users in my offical thread that a new version would be required.
http://forums.keenswh.com/threads/custom-importer-editor-tool-setoolbox.6638984/page-55

Please download the latest version.
