### ISSUE TITLE
Problem Starting Application in Windows 10

### ISSUE THREAD

**Issue by Melodeon** [midspace/SEToolbox#69]
I have installed both ways and checked the .NET build.
On starting SETOOLBOX I receive an error message (attached) and then .. nothing.

![set_capture](https://cloud.githubusercontent.com/assets/20168816/16382955/e7f5e5ca-3c7a-11e6-8a7c-19418481da5d.JPG)

Great tool for those of us addicted to SE..

**Comment by Melodeon** [comment]
As requested.

 

Dave

 

Log Name:      Application

Source:        SEToolbox.exe

Date:          30/06/2016 11:17:34

Event ID:      0

Task Category: None

Level:         Error

Keywords:      Classic

User:          N/A

Computer:      Mega-PC

Description:

2016-06-30 11:17:34,670 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception

Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe

CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 

CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox

SEBinPath: C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Bin64

SEBinVersion: 1.139.8

ProcessorCount: 8

OSVersion: Microsoft Windows NT 6.2.9200.0

Version: 4.0.30319.42000

Is64BitOperatingSystem: True

IntPtr.Size: 8

IsAdmin: False

CurrentUICulture: en-GB

CurrentCulture: en-GB

 

Files:

2016-06-24T17:32:44.7675560+01:00      24,781,752                           HavokWrapper.dll

2016-01-11T16:42:58.0000000+00:00      498,176                 2014.2.17.1         HelixToolkit.Wpf.dll

2016-01-11T16:42:58.0000000+00:00      200,704                 0.86.0.518            ICSharpCode.SharpZipLib.dll

2016-01-11T16:42:58.0000000+00:00      301,056                 1.2.13.0                log4net.dll

2016-06-24T17:32:47.4739279+01:00      47,032   1.0.0.0   Sandbox.Common.dll

2016-06-24T17:32:59.5634244+01:00      5,641,144             1.0.0.0   Sandbox.Game.dll

2016-06-24T17:32:49.9017575+01:00      297,400                 1.0.0.0   Sandbox.Graphics.dll

2016-06-15T20:59:26.0000000+01:00      1,245,184             01.138.004.1       SEToolbox.exe

2016-06-15T18:45:08.0000000+01:00      745                         SEToolbox.exe.config

2016-04-07T19:39:42.0000000+01:00      27,648   1.0.0.0   SEToolbox.ImageLibrary.dll

2016-06-15T20:59:22.0000000+01:00      7,680     1.0.0.0   SEToolbox.ImageShaders.dll

2016-06-15T20:59:26.0000000+01:00      2,471,424                             SEToolbox.pdb

2016-06-15T20:48:48.0000000+01:00      51,712   1.0.0.0   SEToolboxUpdate.exe

2016-06-24T17:32:59.5833920+01:00      262,072                 3.0.1      SharpDX.dll

2016-06-24T17:32:54.6761414+01:00      326,584                 1.0.0.0   SpaceEngineers.Game.dll

2016-06-24T17:32:55.1345519+01:00      50,616   1.0.0.0   SpaceEngineers.ObjectBuilders.dll

2016-06-24T17:33:01.2723621+01:00      10,197,944           1.0.0.0   SpaceEngineers.ObjectBuilders.XmlSerializers.dll

2016-06-24T17:33:02.9954694+01:00      537,016                                 SteamSDK.dll

2016-04-27T14:23:07.1887568+01:00      105,152                 02.19.34.93         steam_api.dll

2016-04-27T14:20:47.4485208+01:00      119,488                 02.19.34.93         steam_api64.dll

2016-01-11T16:42:58.0000000+00:00      39,936   2.0.20525.0         System.Windows.Interactivity.dll

2016-06-24T17:32:52.3734455+01:00      640,440                 1.0.0.0   VRage.dll

2016-06-24T17:32:57.0317998+01:00      710,072                 1.0.0.0   VRage.Game.dll

2016-06-24T17:33:03.6886376+01:00      2,633,144             1.0.0.0   VRage.Game.XmlSerializers.dll

2016-06-24T17:32:52.1621480+01:00      94,136   1.0.0.0   VRage.Input.dll

2016-06-24T17:33:05.7020593+01:00      638,904                 1.0.0.0   VRage.Library.dll

2016-06-24T17:32:53.3904726+01:00      471,992                 1.0.0.0   VRage.Math.dll

2016-06-24T17:33:04.2712091+01:00      73,144                   VRage.Native.dll

2016-06-24T17:32:55.8741620+01:00      103,352                 1.0.0.0   VRage.OpenVRWrapper.dll

2016-06-24T17:32:53.8223991+01:00      523,192                 1.0.0.0   VRage.Render.dll

2016-01-11T16:42:58.0000000+00:00      64,512   2.2.0      WPFLocalizeExtension.dll

2016-01-11T16:42:58.0000000+00:00      26,624   1.1.6.3   XAMLMarkupExtensions.dll

 

System.TypeInitializationException: The type initializer for 'SEToolbox.Interop.SpaceEngineersCore' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SteamSDK.dll' or one of its dependencies. The specified module could not be found.

   at Sandbox.MySandboxGame..ctor(VRageGameServices services, String[] commandlineArgs)

   at SEToolbox.Interop.SpaceEngineersCore..ctor() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 46

   at SEToolbox.Interop.SpaceEngineersCore..cctor() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 20

   --- End of inner exception stack trace ---

   at SEToolbox.Interop.SpaceEngineersCore.LoadDefinitions()

   at SEToolbox.CoreToolbox.Load(String[] args) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\CoreToolbox.cs:line 181

   at SEToolbox.App.OnStartup(Object sender, StartupEventArgs e) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\App.xaml.cs:line 94

   at System.Windows.Application.OnStartup(StartupEventArgs e)

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

 

Event Xml:

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">

  <System>

    <Provider Name="SEToolbox.exe" />

    <EventID Qualifiers="0">0</EventID>

    <Level>2</Level>

    <Task>0</Task>

    <Keywords>0x80000000000000</Keywords>

    <TimeCreated SystemTime="2016-06-30T10:17:34.702084100Z" />

    <EventRecordID>4598</EventRecordID>

    <Channel>Application</Channel>

    <Computer>Mega-PC</Computer>

    <Security />

  </System>

  <EventData>

    <Data>2016-06-30 11:17:34,670 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception

Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe

CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 

CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox

SEBinPath: C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Bin64

SEBinVersion: 1.139.8

ProcessorCount: 8

OSVersion: Microsoft Windows NT 6.2.9200.0

Version: 4.0.30319.42000

Is64BitOperatingSystem: True

IntPtr.Size: 8

IsAdmin: False

CurrentUICulture: en-GB

CurrentCulture: en-GB

 

Files:

2016-06-24T17:32:44.7675560+01:00      24,781,752                           HavokWrapper.dll

2016-01-11T16:42:58.0000000+00:00      498,176                 2014.2.17.1         HelixToolkit.Wpf.dll

2016-01-11T16:42:58.0000000+00:00      200,704                 0.86.0.518            ICSharpCode.SharpZipLib.dll

2016-01-11T16:42:58.0000000+00:00      301,056                 1.2.13.0                log4net.dll

2016-06-24T17:32:47.4739279+01:00      47,032   1.0.0.0   Sandbox.Common.dll

2016-06-24T17:32:59.5634244+01:00      5,641,144             1.0.0.0   Sandbox.Game.dll

2016-06-24T17:32:49.9017575+01:00      297,400                 1.0.0.0   Sandbox.Graphics.dll

2016-06-15T20:59:26.0000000+01:00      1,245,184             01.138.004.1       SEToolbox.exe

2016-06-15T18:45:08.0000000+01:00      745                         SEToolbox.exe.config

2016-04-07T19:39:42.0000000+01:00      27,648   1.0.0.0   SEToolbox.ImageLibrary.dll

2016-06-15T20:59:22.0000000+01:00      7,680     1.0.0.0   SEToolbox.ImageShaders.dll

2016-06-15T20:59:26.0000000+01:00      2,471,424                             SEToolbox.pdb

2016-06-15T20:48:48.0000000+01:00      51,712   1.0.0.0   SEToolboxUpdate.exe

2016-06-24T17:32:59.5833920+01:00      262,072                 3.0.1      SharpDX.dll

2016-06-24T17:32:54.6761414+01:00      326,584                 1.0.0.0   SpaceEngineers.Game.dll

2016-06-24T17:32:55.1345519+01:00      50,616   1.0.0.0   SpaceEngineers.ObjectBuilders.dll

2016-06-24T17:33:01.2723621+01:00      10,197,944           1.0.0.0   SpaceEngineers.ObjectBuilders.XmlSerializers.dll

2016-06-24T17:33:02.9954694+01:00      537,016                                 SteamSDK.dll

2016-04-27T14:23:07.1887568+01:00      105,152                 02.19.34.93         steam_api.dll

2016-04-27T14:20:47.4485208+01:00      119,488                 02.19.34.93         steam_api64.dll

2016-01-11T16:42:58.0000000+00:00      39,936   2.0.20525.0         System.Windows.Interactivity.dll

2016-06-24T17:32:52.3734455+01:00      640,440                 1.0.0.0   VRage.dll

2016-06-24T17:32:57.0317998+01:00      710,072                 1.0.0.0   VRage.Game.dll

2016-06-24T17:33:03.6886376+01:00      2,633,144             1.0.0.0   VRage.Game.XmlSerializers.dll

2016-06-24T17:32:52.1621480+01:00      94,136   1.0.0.0   VRage.Input.dll

2016-06-24T17:33:05.7020593+01:00      638,904                 1.0.0.0   VRage.Library.dll

2016-06-24T17:32:53.3904726+01:00      471,992                 1.0.0.0   VRage.Math.dll

2016-06-24T17:33:04.2712091+01:00      73,144                   VRage.Native.dll

2016-06-24T17:32:55.8741620+01:00      103,352                 1.0.0.0   VRage.OpenVRWrapper.dll

2016-06-24T17:32:53.8223991+01:00      523,192                 1.0.0.0   VRage.Render.dll

2016-01-11T16:42:58.0000000+00:00      64,512   2.2.0      WPFLocalizeExtension.dll

2016-01-11T16:42:58.0000000+00:00      26,624   1.1.6.3   XAMLMarkupExtensions.dll

 

System.TypeInitializationException: The type initializer for 'SEToolbox.Interop.SpaceEngineersCore' threw an exception. ---&gt; System.IO.FileNotFoundException: Could not load file or assembly 'SteamSDK.dll' or one of its dependencies. The specified module could not be found.

   at Sandbox.MySandboxGame..ctor(VRageGameServices services, String[] commandlineArgs)

   at SEToolbox.Interop.SpaceEngineersCore..ctor() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 46

   at SEToolbox.Interop.SpaceEngineersCore..cctor() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 20

   --- End of inner exception stack trace ---

   at SEToolbox.Interop.SpaceEngineersCore.LoadDefinitions()

   at SEToolbox.CoreToolbox.Load(String[] args) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\CoreToolbox.cs:line 181

   at SEToolbox.App.OnStartup(Object sender, StartupEventArgs e) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\App.xaml.cs:line 94

   at System.Windows.Application.OnStartup(StartupEventArgs e)

   at System.Windows.Application.&lt;.ctor&gt;b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

</Data>

  </EventData>

</Event>

**Comment by midspace** [comment]
It took me some time to find a clean machine to test this one.

It looks like SEToolbox required 2 more files from the Space Engineers installation to run.
I will be making a fix for this in the next 48 hours, so SEToolbox finds the files.

In the meantime, the quick fix is to **copy** the following two files...
`msvcp120.dll`
`msvcr120.dll`

From your Space Engineers path...
`C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Bin64`

Into the SEToolbox path...
`C:\Program Files (x86)\MidSpace\SEToolbox\`

Windows may ask for UAC permission to copy files into that location.
You will need to press `Yes` to confirm.

**Comment by Melodeon** [comment]
Thank you for your reply.

 

I am travelling at the moment but will get back to you when I return to try the fix out.

 

Dave

**Comment by midspace** [comment]
I have just published a new release. Please download and try it.
https://github.com/midspace/SEToolbox/releases/latest

**Comment by Melodeon** [comment]
New version now works for me.

 

Thank you.

 

Dave
