### ISSUE TITLE
SEToolbox crashes in Develop branch 1.157

### ISSUE THREAD

**Issue by midspace** [midspace/SEToolbox#83]
Version 1.157 (develpo branch) of Space Engineers will cause SEToolbox to crash.
It will require a rebuild of the solution to fix the issue. No code changes required. Obviously some of the SE code has been moved around causing dependency issues in SEToolbox.

`System.TypeInitializationException: The type initializer for 'SEToolbox.Interop.SpaceEngineersCore' threw an exception. ---> System.MissingMethodException: Method not found: 'Void VRage.FileSystem.MyFileSystem.Init(System.String, System.String, System.String)'.
   at SEToolbox.Interop.SpaceEngineersCore..ctor()
   at SEToolbox.Interop.SpaceEngineersCore..cctor() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 20
   --- End of inner exception stack trace ---
   at SEToolbox.Interop.SpaceEngineersCore.LoadDefinitions()
   at SEToolbox.CoreToolbox.Load(String[] args) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\CoreToolbox.cs:line 181
   at SEToolbox.App.OnStartup(Object sender, StartupEventArgs e) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\App.xaml.cs:line 94
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by midspace** [comment]
Was rebuilt an released without issue.
