### ISSUE TITLE
The type initializer for 'SEToolbox.Interop.SpaceEngineersCore' threw an exception

### ISSUE THREAD

**Issue by ajud123** [midspace/SEToolbox#85]
I get this when I try to start SEToolbox. Event log:
2016-11-08 17:46:35,705 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Users\%USERNAME%\Downloads\spaceEngineer\SEToolbox\SEToolbox.exe
CommandLine: "C:\Users\%USERNAME%\Downloads\spaceEngineer\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Users\%USERNAME%\Downloads\spaceEngineer\SEToolbox
SEBinPath: C:\Users\Audrius\Downloads\spaceEngineer\Space.Engineers.v01.159.006\Bin64
SEBinVersion: 1.159.6
ProcessorCount: 4
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-GB
CurrentCulture: en-GB

Files:
2016-10-28T11:18:32.0000000+03:00	21,522,360		HavokWrapper.dll
2016-01-11T09:42:57.2807547+02:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2016-01-11T09:42:57.2827548+02:00	200,704	0.86.0.518	ICSharpCode.SharpZipLib.dll
2016-01-11T09:42:57.2887551+02:00	301,056	1.2.13.0	log4net.dll
2016-10-07T02:23:43.0000000+03:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2016-10-07T02:23:44.0000000+03:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2016-10-28T11:18:17.0000000+03:00	53,688	1.0.0.0	Sandbox.Common.dll
2016-10-28T11:18:20.0000000+03:00	6,055,864	1.0.0.0	Sandbox.Game.dll
2016-10-28T11:18:17.0000000+03:00	318,392	1.0.0.0	Sandbox.Graphics.dll
2016-10-15T02:26:04.8651520+03:00	1,205,248	01.153.010.1	SEToolbox.exe
2016-06-15T11:45:07.4287495+03:00	745		SEToolbox.exe.config
2016-09-26T02:21:47.8933694+03:00	27,136	1.0.0.0	SEToolbox.ImageLibrary.dll
2016-10-15T02:26:01.3991109+03:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2016-10-15T02:26:04.8471512+03:00	2,043,392		SEToolbox.pdb
2016-10-15T02:26:01.1057691+03:00	51,200	1.0.0.0	SEToolboxUpdate.exe
2016-10-28T11:18:17.0000000+03:00	262,072	3.0.1	SharpDX.dll
2016-10-28T11:18:18.0000000+03:00	337,848	1.0.0.0	SpaceEngineers.Game.dll
2016-10-28T11:18:18.0000000+03:00	51,640	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2016-10-28T11:18:24.0000000+03:00	10,808,760	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2016-10-28T11:18:17.0000000+03:00	537,016		SteamSDK.dll
2014-05-20T23:21:34.0000000+03:00	100,864	02.01.77.37	steam_api.dll
2014-05-20T23:20:46.0000000+03:00	116,736	02.01.77.37	steam_api64.dll
2016-01-11T09:42:57.2837548+02:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2016-10-28T11:18:19.0000000+03:00	69,048	1.0.0.0	VRage.Audio.dll
2016-10-28T11:18:18.0000000+03:00	374,712	1.0.0.0	VRage.dll
2016-10-28T11:18:19.0000000+03:00	907,704	1.0.0.0	VRage.Game.dll
2016-10-28T11:18:20.0000000+03:00	3,037,112	1.0.0.0	VRage.Game.XmlSerializers.dll
2016-10-28T11:18:19.0000000+03:00	95,160	1.0.0.0	VRage.Input.dll
2016-10-28T11:18:19.0000000+03:00	656,312	1.0.0.0	VRage.Library.dll
2016-10-28T11:18:19.0000000+03:00	509,368	1.0.0.0	VRage.Math.dll
2016-10-28T11:18:18.0000000+03:00	76,728		VRage.Native.dll
2016-10-28T11:18:18.0000000+03:00	103,352	1.0.0.0	VRage.OpenVRWrapper.dll
2016-10-28T11:18:18.0000000+03:00	324,536	1.0.0.0	VRage.Render.dll
2016-10-28T11:18:19.0000000+03:00	715,192	1.0.0.0	VRage.Render11.dll
2016-01-11T09:42:57.2847549+02:00	64,512	2.2.0	WPFLocalizeExtension.dll
2016-01-11T09:42:57.2857549+02:00	26,624	1.1.6.3	XAMLMarkupExtensions.dll

System.TypeInitializationException: The type initializer for 'SEToolbox.Interop.SpaceEngineersCore' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SteamSDK.dll' or one of its dependencies. The specified module could not be found.
   at Sandbox.MySandboxGame..ctor(VRageGameServices services, String[] commandlineArgs)
   at SEToolbox.Interop.SpaceEngineersCore..ctor() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 46
   at SEToolbox.Interop.SpaceEngineersCore..cctor() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\SpaceEngineersCore.cs:line 20
   --- End of inner exception stack trace ---
   at SEToolbox.Interop.SpaceEngineersCore.LoadDefinitions()
   at SEToolbox.CoreToolbox.Load(String[] args) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\CoreToolbox.cs:line 181
   at SEToolbox.App.OnStartup(Object sender, StartupEventArgs e) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\App.xaml.cs:line 94
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

The game is completely unmodded. That means I did not install any mods before

**Comment by midspace** [comment]
The current version of public is 1.153.011
The current version of the develop branch is 1.160.005
The version of the game you appear to have is not current. 1.159.006

Both of the currents versions share identical steam_api.dll and steam_api64.dll.
The version you appear to have is different, and is not recognised.
I can't help you if you are using modified game files.

**Comment by ajud123** [comment]
ok

**Comment by midspace** [comment]
I should say, if you have a friend who is a programmer and has the same copy of the game, you should be able to compile a version of SEToolbox for yourself.
