### ISSUE TITLE
1.153.10.1 Error

### ISSUE THREAD

**Issue by DonMarco** [midspace/SEToolbox#87]
![image](https://cloud.githubusercontent.com/assets/4727267/20948002/097017fe-bc12-11e6-9949-4efbcecd9d44.png)

What to do?

**Comment by midspace** [comment]
Sorry, you'll have to provide a copy of the Event Log described here:
https://github.com/midspace/SEToolbox/wiki/Reporting-bugs

Or provide a copy of your save game.

**Comment by DonMarco** [comment]
> The description for Event ID 0 from source SEToolbox.exe cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

2016-12-07 00:08:51,978 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: C:\Games\Steam\SteamApps\common\SpaceEngineers\Bin64
SEBinVersion: 1.157.13
ProcessorCount: 8
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: 
CurrentCulture: 

Files:
2016-11-25T21:38:16.0446030+01:00	21,522,360		HavokWrapper.dll
2016-01-11T18:42:58.0000000+01:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2016-01-11T18:42:58.0000000+01:00	200,704	0.86.0.518	ICSharpCode.SharpZipLib.dll
2016-01-11T18:42:58.0000000+01:00	301,056	1.2.13.0	log4net.dll
2015-11-16T00:15:44.9492286+01:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2015-11-16T00:16:18.0055824+01:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2016-11-25T21:38:09.9393744+01:00	53,688	1.0.0.0	Sandbox.Common.dll
2016-11-25T21:38:12.3724477+01:00	6,058,424	1.0.0.0	Sandbox.Game.dll
2016-11-25T21:38:09.9358659+01:00	318,392	1.0.0.0	Sandbox.Graphics.dll
2016-10-15T11:26:06.0000000+02:00	1,205,248	01.153.010.1	SEToolbox.exe
2016-06-15T20:45:08.0000000+02:00	745		SEToolbox.exe.config
2016-09-26T11:21:48.0000000+02:00	27,136	1.0.0.0	SEToolbox.ImageLibrary.dll
2016-10-15T11:26:02.0000000+02:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2016-10-15T11:26:06.0000000+02:00	2,043,392		SEToolbox.pdb
2016-10-15T11:26:02.0000000+02:00	51,200	1.0.0.0	SEToolboxUpdate.exe
2016-11-25T21:38:06.4699967+01:00	262,072	3.0.1	SharpDX.dll
2016-11-25T21:38:06.4689936+01:00	337,848	1.0.0.0	SpaceEngineers.Game.dll
2016-11-25T21:38:06.4704972+01:00	51,640	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2016-11-25T21:38:16.0456073+01:00	10,808,248	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2016-11-25T21:38:16.0476249+01:00	537,016		SteamSDK.dll
2015-11-16T00:16:02.3483416+01:00	105,152	02.19.34.93	steam_api.dll
2015-11-16T00:15:49.5007934+01:00	119,488	02.19.34.93	steam_api64.dll
2016-01-11T18:42:58.0000000+01:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2016-11-25T21:38:11.2339588+01:00	69,048	1.0.0.0	VRage.Audio.dll
2016-11-25T21:38:08.4819872+01:00	375,224	1.0.0.0	VRage.dll
2016-11-25T21:38:12.3734491+01:00	905,656	1.0.0.0	VRage.Game.dll
2016-11-25T21:38:16.0491150+01:00	3,032,504	1.0.0.0	VRage.Game.XmlSerializers.dll
2016-11-25T21:38:11.2314490+01:00	95,160	1.0.0.0	VRage.Input.dll
2016-11-25T21:38:16.0531257+01:00	654,776	1.0.0.0	VRage.Library.dll
2016-11-25T21:38:06.4714999+01:00	509,368	1.0.0.0	VRage.Math.dll
2016-11-25T21:38:07.4958704+01:00	76,728		VRage.Native.dll
2016-11-25T21:38:07.4953715+01:00	103,352	1.0.0.0	VRage.OpenVRWrapper.dll
2016-11-25T21:38:07.4948697+01:00	324,024	1.0.0.0	VRage.Render.dll
2016-11-25T21:38:11.2299438+01:00	678,840	1.0.0.0	VRage.Render11.dll
2016-01-11T18:42:58.0000000+01:00	64,512	2.2.0	WPFLocalizeExtension.dll
2016-01-11T18:42:58.0000000+01:00	26,624	1.1.6.3	XAMLMarkupExtensions.dll

System.ArgumentException: '514285714285714' is not a valid value for this property. Valid values are from Int32.MinValue through Int32.MaxValue.
   at System.Windows.Window.ValidateTopLeft(Double length)
   at System.Windows.Window.CoerceLeft(DependencyObject d, Object value)
   at System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Window.set_Left(Double value)
   at SEToolbox.CoreToolbox.<>c__DisplayClass1_0.<Load>b__2(Object sender, RoutedEventArgs e) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\CoreToolbox.cs:line 206
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

The toolbox has been reinstalled and installed several times...

**Comment by midspace** [comment]
Hold down 'SHIFT' when you start SEToolbox up.
It should fix this issue.

https://github.com/midspace/SEToolbox/wiki/Frequently-Asked-Questions#other-issues
